# Generated By: Claude Code (Claude Opus 4.6)
"""Shared fixtures for local_transcribe tests."""

import numpy as np
import pytest
from unittest.mock import MagicMock, patch

from local_transcribe.transcription import SAMPLE_RATE


@pytest.fixture
def silence_audio():
    """1 second of silence at SAMPLE_RATE."""
    return np.zeros(SAMPLE_RATE, dtype=np.int16)


@pytest.fixture
def speech_audio():
    """1 second of loud audio (well above silence threshold)."""
    return np.full(SAMPLE_RATE, 10000, dtype=np.int16)


@pytest.fixture
def mock_recording_session():
    """A RecordingSession with mocked device access."""
    mock_sd = MagicMock()
    with (
        patch("local_transcribe.recording.get_default_input_device", return_value=0),
        patch("local_transcribe.recording._sd", return_value=mock_sd),
    ):
        from local_transcribe.recording import RecordingSession

        session = RecordingSession(device_id=0)
        yield session


@pytest.fixture
def mock_whisper_model():
    """A mock WhisperModel that returns predictable segments."""

    class FakeSegment:
        def __init__(self, text, end):
            self.text = text
            self.end = end

    model = MagicMock()
    model.transcribe.return_value = (
        iter([FakeSegment("hello world", 1.0)]),
        None,
    )
    return model
