# Generated By: Claude Code (Claude Opus 4.6)
"""Shared fixtures and autouse safety guards for local_transcribe tests."""

import subprocess
from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from local_transcribe.transcription import SAMPLE_RATE

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def _block_subprocess(request: pytest.FixtureRequest):
    """Block subprocess; opt in via @pytest.mark.requires_subprocess."""
    if "requires_subprocess" in request.keywords:
        yield
        return

    def _blocked(*args, **kwargs):
        cmd = args[0] if args else kwargs.get("args", "?")
        raise RuntimeError(
            f"subprocess blocked by conftest: {cmd!r}. Mock it, or add"
            " @pytest.mark.requires_subprocess if a real spawn is needed."
        )

    with (
        patch.object(subprocess, "run", side_effect=_blocked),
        patch.object(subprocess, "Popen", side_effect=_blocked),
        patch.object(subprocess, "call", side_effect=_blocked),
        patch.object(subprocess, "check_call", side_effect=_blocked),
        patch.object(subprocess, "check_output", side_effect=_blocked),
    ):
        yield


@pytest.fixture(autouse=True)
def _block_real_filesystem(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Prevent tests from writing outside tmp_path (and the project's .venv)."""
    tmp_str = str(tmp_path.resolve())
    venv_str = str((_PROJECT_ROOT / ".venv").resolve())

    def _is_allowed(path: Path) -> bool:
        try:
            resolved = str(path.resolve())
        except (OSError, ValueError):
            return False
        return resolved.startswith(tmp_str) or resolved.startswith(venv_str)

    def _guard(original):
        def guarded(self, *args, **kwargs):
            if not _is_allowed(self):
                raise PermissionError(f"Test tried to write outside tmp_path: {self}")
            return original(self, *args, **kwargs)

        return guarded

    for method in ("write_text", "write_bytes", "rename", "unlink", "rmdir", "mkdir"):
        monkeypatch.setattr(Path, method, _guard(getattr(Path, method)))


@pytest.fixture
def silence_audio():
    """1 second of silence at SAMPLE_RATE."""
    return np.zeros(SAMPLE_RATE, dtype=np.int16)


@pytest.fixture
def speech_audio():
    """1 second of loud audio (well above silence threshold)."""
    return np.full(SAMPLE_RATE, 10000, dtype=np.int16)


@pytest.fixture
def mock_recording_session():
    """A RecordingSession with mocked device access."""
    mock_sd = MagicMock()
    with (
        patch("local_transcribe.recording.get_default_input_device", return_value=0),
        patch("local_transcribe.recording._sd", return_value=mock_sd),
    ):
        from local_transcribe.recording import RecordingSession

        session = RecordingSession(device_id=0)
        yield session


class FakeSegment:
    """Mimics a faster-whisper Segment for test mocking."""

    def __init__(self, text, start, end):
        self.text = text
        self.start = start
        self.end = end


@pytest.fixture
def mock_whisper_model():
    """A mock WhisperModel that returns predictable segments."""
    model = MagicMock()
    model.transcribe.return_value = (
        iter([FakeSegment("hello world", 0.0, 1.0)]),
        None,
    )
    return model
