# Generated By: Claude Code (claude-opus-5)
"""Tests for scripts/version-bump.sh."""

import shutil
import subprocess
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "version-bump.sh"
VERSION_FILES = ["pkg_a/__init__.py", "pkg_b/__init__.py"]


def _project(tmp_path, version="1.2.3"):
    """Build a throwaway project with pyproject.toml and two version files."""
    (tmp_path / "pyproject.toml").write_text(
        f'[project]\nname = "demo"\nversion = "{version}"\n'
        f'dependencies = [\n    "av>=10.0.0",\n]\n'
    )
    for rel in VERSION_FILES:
        path = tmp_path / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f'"""Demo."""\n\n__version__ = "{version}"\n')
    return tmp_path


def _bump(tmp_path, part, files=VERSION_FILES):
    return subprocess.run(
        ["bash", str(SCRIPT), part, *files],
        cwd=tmp_path,
        capture_output=True,
        text=True,
    )


def _versions(tmp_path):
    """Every version string in the project, pyproject first."""
    found = [
        line.split('"')[1]
        for line in (tmp_path / "pyproject.toml").read_text().splitlines()
        if line.startswith("version")
    ]
    for rel in VERSION_FILES:
        for line in (tmp_path / rel).read_text().splitlines():
            if line.startswith("__version__"):
                found.append(line.split('"')[1])
    return found


@pytest.mark.requires_subprocess
class TestVersionBump:
    @pytest.mark.parametrize(
        "part,expected",
        [("major", "2.0.0"), ("minor", "1.3.0"), ("patch", "1.2.4")],
    )
    def test_bumps_all_files_in_step(self, tmp_path, part, expected):
        project = _project(tmp_path)
        result = _bump(project, part)

        assert result.returncode == 0, result.stderr
        assert _versions(project) == [expected] * 3
        assert "1.2.3 -> " + expected in result.stdout

    def test_minor_and_patch_reset_lower_parts(self, tmp_path):
        project = _project(tmp_path, version="1.9.9")
        assert _bump(project, "major").returncode == 0
        assert _versions(project) == ["2.0.0"] * 3

    def test_rejects_unknown_part(self, tmp_path):
        project = _project(tmp_path)
        result = _bump(project, "pacth")

        assert result.returncode == 1
        assert "expected major, minor, or patch" in result.stderr
        assert _versions(project) == ["1.2.3"] * 3

    def test_rejects_prerelease_version(self, tmp_path):
        project = _project(tmp_path, version="1.2.3-rc1")
        result = _bump(project, "patch")

        assert result.returncode == 1
        assert "not a plain MAJOR.MINOR.PATCH" in result.stderr

    def test_missing_version_file_writes_nothing(self, tmp_path):
        project = _project(tmp_path)
        result = _bump(project, "patch", files=VERSION_FILES + ["pkg_c/__init__.py"])

        assert result.returncode == 1
        assert "no such version file" in result.stderr
        # pyproject must not be left ahead of the packages.
        assert _versions(project) == ["1.2.3"] * 3

    def test_only_the_version_line_changes(self, tmp_path):
        project = _project(tmp_path)
        before = (project / "pyproject.toml").read_text()
        assert _bump(project, "patch").returncode == 0
        after = (project / "pyproject.toml").read_text()

        assert before.replace('"1.2.3"', '"1.2.4"') == after
        # "av>=10.0.0" must survive — it looks version-ish to a sloppy sed.
        assert '"av>=10.0.0"' in after


@pytest.mark.requires_subprocess
class TestVersionCheckAcceptsMultipleFiles:
    def test_flags_a_drifting_second_package(self, tmp_path):
        project = _project(tmp_path)
        shutil.copy(SCRIPT.parent / "version-check.sh", project / "version-check.sh")
        (project / VERSION_FILES[1]).write_text('__version__ = "9.9.9"\n')

        result = subprocess.run(
            ["bash", "version-check.sh", " ".join(VERSION_FILES)],
            cwd=project,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 1
        assert "pkg_b/__init__.py has '9.9.9'" in result.stderr
