# Generated By: Claude Code (claude-opus-5)
"""Tests for the --device error hint in local_transcribe_ui.__main__."""

import pytest
from unittest.mock import patch

from local_transcribe_ui.__main__ import main

_HINT = "local-transcribe devices"


def _run(argv, capsys):
    """Run main() with argv and return (exit_code, stderr)."""
    with patch("sys.argv", ["local-transcribe"] + argv):
        with pytest.raises(SystemExit) as exc:
            main()
    return exc.value.code, capsys.readouterr().err


class TestDeviceHint:
    def test_missing_value_suggests_devices_command(self, capsys):
        code, err = _run(["record", "--device"], capsys)
        assert code == 2
        assert "expected one argument" in err
        assert _HINT in err

    def test_non_integer_value_suggests_devices_command(self, capsys):
        code, err = _run(["record", "--device", "abc"], capsys)
        assert code == 2
        assert _HINT in err

    def test_unrelated_error_has_no_hint(self, capsys):
        code, err = _run(["record", "--compute-device"], capsys)
        assert code == 2
        assert _HINT not in err
