# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe_ui.settings module."""

import json

from local_transcribe_ui.settings import Settings, load_settings, save_settings


class TestSettings:
    def test_defaults(self):
        s = Settings()
        assert s.window_x is None
        assert s.window_y is None

    def test_saves_and_reloads(self, tmp_path):
        path = tmp_path / "settings.json"
        original = Settings(window_x=100, window_y=200)
        save_settings(original, path=path)

        loaded = load_settings(path=path)
        assert loaded.window_x == 100
        assert loaded.window_y == 200

    def test_returns_defaults_when_missing(self, tmp_path):
        path = tmp_path / "nonexistent.json"
        settings = load_settings(path=path)
        assert settings == Settings()

    def test_returns_defaults_on_corrupt_json(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text("{invalid json", encoding="utf-8")
        settings = load_settings(path=path)
        assert settings == Settings()

    def test_ignores_unknown_fields(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text(
            json.dumps({"unknown_field": 42, "window_x": 50}), encoding="utf-8"
        )
        settings = load_settings(path=path)
        assert settings.window_x == 50
        assert not hasattr(settings, "unknown_field")

    def test_none_default_accepts_any_type(self, tmp_path):
        # None-default fields accept any type per settings standard
        path = tmp_path / "settings.json"
        path.write_text(json.dumps({"window_x": "not_an_int"}), encoding="utf-8")
        settings = load_settings(path=path)
        assert settings.window_x == "not_an_int"

    def test_creates_directory_on_save(self, tmp_path):
        path = tmp_path / "subdir" / "settings.json"
        save_settings(Settings(window_x=10), path=path)
        assert path.exists()

    def test_atomic_write(self, tmp_path):
        path = tmp_path / "settings.json"
        save_settings(Settings(window_x=1), path=path)
        save_settings(Settings(window_x=2), path=path)
        loaded = load_settings(path=path)
        assert loaded.window_x == 2
        # No .tmp file left behind
        assert not (tmp_path / "settings.tmp").exists()

    def test_empty_file_returns_defaults(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text("", encoding="utf-8")
        settings = load_settings(path=path)
        assert settings == Settings()

    def test_non_dict_json_returns_defaults(self, tmp_path):
        path = tmp_path / "settings.json"
        path.write_text("[1, 2, 3]", encoding="utf-8")
        settings = load_settings(path=path)
        assert settings == Settings()
