# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe.transcription module."""

import wave

import numpy as np
import pytest
from unittest.mock import MagicMock, patch

from local_transcribe.transcription import (
    AUDIO_CHANNELS,
    AUDIO_SAMPLE_WIDTH,
    SAMPLE_RATE,
    _sanitize_transcript,
    compute_audio_level,
    save_wav_to,
)


class TestComputeAudioLevel:
    def test_zero_peak(self):
        assert compute_audio_level(0) == 0.0

    def test_max_peak(self):
        assert compute_audio_level(32768) == 1.0

    def test_mid_peak(self):
        # With gain=1.0, half-max should be ~0.5
        level = compute_audio_level(16384, gain=1.0)
        assert 0.49 < level < 0.51

    def test_default_gain_amplifies(self):
        # With default gain of 4.0, quarter-max should reach 1.0
        assert compute_audio_level(8192) == 1.0

    def test_clamps_to_one(self):
        assert compute_audio_level(50000) == 1.0

    def test_custom_gain(self):
        level = compute_audio_level(16384, gain=1.0)
        assert 0.49 < level < 0.51

    def test_high_gain(self):
        assert compute_audio_level(4096, gain=8.0) == 1.0


class TestSaveWavTo:
    def test_creates_valid_wav(self, tmp_path):
        audio = np.zeros(SAMPLE_RATE, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with wave.open(path, "rb") as wf:
            assert wf.getnchannels() == AUDIO_CHANNELS
            assert wf.getsampwidth() == AUDIO_SAMPLE_WIDTH
            assert wf.getframerate() == SAMPLE_RATE
            assert wf.getnframes() == SAMPLE_RATE


class TestSanitizeTranscript:
    def test_ascii_unchanged(self):
        with patch("local_transcribe.transcription.sys") as mock_sys:
            mock_sys.stdout.encoding = "utf-8"
            assert _sanitize_transcript("hello world") == "hello world"

    def test_replaces_unencodable_chars_on_cp1252(self):
        with patch("local_transcribe.transcription.sys") as mock_sys:
            mock_sys.stdout.encoding = "cp1252"
            result = _sanitize_transcript("\u10d0\u10d1\u10d2")
            assert "\u10d0" not in result
            assert result == "???"

    def test_empty_string(self):
        with patch("local_transcribe.transcription.sys") as mock_sys:
            mock_sys.stdout.encoding = "utf-8"
            assert _sanitize_transcript("") == ""


class TestRunTranscription:
    """Unit tests for transcription functions with mocked model."""

    def test_transcribe_wav_with_mock(self, tmp_path, mock_whisper_model):
        from local_transcribe.transcription import transcribe_wav

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            result = transcribe_wav(path, model_size="tiny")

        assert result == "hello world"
        mock_whisper_model.transcribe.assert_called_once()

    def test_transcribe_wav_passes_vad_filter(self, tmp_path, mock_whisper_model):
        from local_transcribe.transcription import transcribe_wav

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            transcribe_wav(path, model_size="tiny", vad_filter=True)

        call_kwargs = mock_whisper_model.transcribe.call_args[1]
        assert call_kwargs["vad_filter"] is True

    def test_transcribe_wav_passes_condition_on_previous_text(
        self, tmp_path, mock_whisper_model
    ):
        from local_transcribe.transcription import transcribe_wav

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            transcribe_wav(path, model_size="tiny", condition_on_previous_text=False)

        call_kwargs = mock_whisper_model.transcribe.call_args[1]
        assert call_kwargs["condition_on_previous_text"] is False

    def test_transcribe_wav_progress_callback(self, tmp_path, mock_whisper_model):
        from local_transcribe.transcription import transcribe_wav

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        progress_values = []
        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            transcribe_wav(
                path,
                model_size="tiny",
                progress_callback=lambda f: progress_values.append(f),
            )

        assert progress_values[-1] == 1.0

    def test_transcribe_audio_with_mock(self, mock_whisper_model):
        from local_transcribe.transcription import transcribe_audio

        audio = np.zeros(SAMPLE_RATE, dtype=np.int16)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            result = transcribe_audio(audio, model_size="tiny")

        assert result == "hello world"
        call_args = mock_whisper_model.transcribe.call_args
        source = call_args[0][0]
        assert source.dtype == np.float32

    def test_transcribe_audio_defaults_vad_on(self, mock_whisper_model):
        from local_transcribe.transcription import transcribe_audio

        audio = np.zeros(SAMPLE_RATE, dtype=np.int16)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            transcribe_audio(audio, model_size="tiny")

        call_kwargs = mock_whisper_model.transcribe.call_args[1]
        assert call_kwargs["vad_filter"] is True
        assert call_kwargs["condition_on_previous_text"] is True

    def test_transcribe_audio_progress_callback(self, mock_whisper_model):
        from local_transcribe.transcription import transcribe_audio

        audio = np.zeros(SAMPLE_RATE, dtype=np.int16)
        progress_values = []

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            transcribe_audio(
                audio,
                model_size="tiny",
                progress_callback=lambda f: progress_values.append(f),
            )

        assert progress_values[-1] == 1.0


class TestGetOrCreateModel:
    def test_caches_model_on_same_size(self):
        from local_transcribe.transcription import get_or_create_model

        mock_cls = MagicMock()
        mock_model = MagicMock()
        mock_cls.return_value = mock_model

        with (
            patch(
                "local_transcribe.transcription._get_model_class", return_value=mock_cls
            ),
            patch("local_transcribe.transcription._cached_model", None),  # noqa: E501
            patch("local_transcribe.transcription._cached_model_key", None),
        ):
            result1 = get_or_create_model(model_size="tiny")
            result2 = get_or_create_model(model_size="tiny")
            assert result1 is mock_model
            assert result2 is mock_model
            assert mock_cls.call_count == 1  # created once, cached on second call

    def test_replaces_model_on_different_size(self):
        from local_transcribe.transcription import get_or_create_model

        mock_cls = MagicMock()
        model_a = MagicMock()
        model_b = MagicMock()
        mock_cls.side_effect = [model_a, model_b]

        with (
            patch(
                "local_transcribe.transcription._get_model_class", return_value=mock_cls
            ),
            patch("local_transcribe.transcription._cached_model", None),  # noqa: E501
            patch("local_transcribe.transcription._cached_model_key", None),
        ):
            result1 = get_or_create_model(model_size="tiny")
            result2 = get_or_create_model(model_size="base")
            assert result1 is model_a
            assert result2 is model_b
            assert mock_cls.call_count == 2


class TestTranscribeWavIntegration:
    """Integration tests — require faster-whisper model download."""

    @pytest.mark.integration
    def test_transcribes_silence_to_empty(self, tmp_path):
        from local_transcribe.transcription import transcribe_wav

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "silence.wav")
        save_wav_to(audio, path)
        result = transcribe_wav(path, model_size="tiny")
        assert isinstance(result, str)


class TestTranscribeAudioIntegration:
    @pytest.mark.integration
    def test_transcribes_silence(self):
        from local_transcribe.transcription import transcribe_audio

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        result = transcribe_audio(audio, model_size="tiny")
        assert isinstance(result, str)
