# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe_ui.lock module."""

import os

import pytest

from local_transcribe_ui.lock import (
    LockAcquireError,
    _read_lock_pid,
    _write_lock_file,
    acquire_lock,
    release_lock,
)


class TestLock:
    def test_acquire_and_release(self, tmp_path):
        lock = tmp_path / "test.lock"
        acquire_lock(path=lock)
        assert lock.exists()
        assert _read_lock_pid(lock) == os.getpid()

        release_lock(path=lock)
        assert not lock.exists()

    def test_acquire_is_idempotent(self, tmp_path):
        lock = tmp_path / "test.lock"
        acquire_lock(path=lock)
        acquire_lock(path=lock)  # same PID, should not raise
        assert _read_lock_pid(lock) == os.getpid()
        release_lock(path=lock)

    def test_stale_lock_is_cleaned(self, tmp_path):
        lock = tmp_path / "test.lock"
        # Write a lock with a PID that doesn't exist
        _write_lock_file(lock, 999999999)
        acquire_lock(path=lock)
        assert _read_lock_pid(lock) == os.getpid()
        release_lock(path=lock)

    def test_live_lock_raises(self, tmp_path):
        lock = tmp_path / "test.lock"
        # Write a lock with our own PID but pretend it's a different process
        # by using a PID we know is alive (PID 1 on Linux, or parent on Windows)
        _write_lock_file(lock, os.getppid())
        with pytest.raises(LockAcquireError, match="Another voice recording"):
            acquire_lock(path=lock)

    def test_release_ignores_unowned(self, tmp_path):
        lock = tmp_path / "test.lock"
        _write_lock_file(lock, 999999999)
        release_lock(path=lock)  # not our PID, should not delete
        assert lock.exists()

    def test_release_missing_file(self, tmp_path):
        lock = tmp_path / "nonexistent.lock"
        release_lock(path=lock)  # should not raise

    def test_creates_parent_directory(self, tmp_path):
        lock = tmp_path / "subdir" / "test.lock"
        acquire_lock(path=lock)
        assert lock.exists()
        release_lock(path=lock)
