# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for _cmd_transcribe in local_transcribe_ui.__main__."""

import argparse
import json

import numpy as np
from unittest.mock import patch

from local_transcribe.transcription import SAMPLE_RATE, save_wav_to


def _make_args(wav_path, output_format="plain"):
    """Build an argparse.Namespace matching _cmd_transcribe expectations."""
    return argparse.Namespace(
        file=wav_path,
        model="tiny",
        compute_device="cpu",
        compute_type="int8",
        vad_filter=True,
        condition_on_previous_text=True,
        output_format=output_format,
        debug=False,
        quiet=True,
        log_file=None,
    )


class TestCmdTranscribePlain:
    def test_plain_output_with_protocol_markers(
        self, tmp_path, mock_whisper_model, capsys
    ):
        from local_transcribe_ui.__main__ import _cmd_transcribe

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            _cmd_transcribe(_make_args(path, "plain"))

        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        assert lines[0].startswith("[BEGIN version=")
        assert lines[-1] == "[END]"
        assert "hello world" in captured.out


class TestCmdTranscribeJson:
    def test_json_output_with_protocol_markers(
        self, tmp_path, mock_whisper_model, capsys
    ):
        from local_transcribe_ui.__main__ import _cmd_transcribe

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=mock_whisper_model,
        ):
            _cmd_transcribe(_make_args(path, "json"))

        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        assert lines[0].startswith("[BEGIN version=")
        assert lines[-1] == "[END]"

        # Extract JSON between protocol markers
        json_text = "\n".join(lines[1:-1])
        segments = json.loads(json_text)

        assert isinstance(segments, list)
        assert len(segments) == 1
        assert segments[0] == {"start": 0.0, "end": 1.0, "text": "hello world"}

    def test_json_output_preserves_unicode(self, tmp_path, capsys):
        from local_transcribe_ui.__main__ import _cmd_transcribe
        from unittest.mock import MagicMock
        from tests.conftest import FakeSegment

        model = MagicMock()
        model.transcribe.return_value = (
            iter([FakeSegment("caf\u00e9 na\u00efvet\u00e9", 0.0, 2.0)]),
            None,
        )

        audio = np.zeros(SAMPLE_RATE * 2, dtype=np.int16)
        path = str(tmp_path / "test.wav")
        save_wav_to(audio, path)

        with patch(
            "local_transcribe.transcription.get_or_create_model",
            return_value=model,
        ):
            _cmd_transcribe(_make_args(path, "json"))

        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        json_text = "\n".join(lines[1:-1])
        segments = json.loads(json_text)
        assert segments[0]["text"] == "caf\u00e9 na\u00efvet\u00e9"
