# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for AppController output protocol."""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from local_transcribe_ui import __version__
from local_transcribe_ui.controller import AppController


@pytest.fixture
def app_controller():
    """An AppController with required args."""
    return AppController(
        model_size="small",
        compute_device="cpu",
        compute_type="int8",
        silence_threshold=0.08,
        silence_duration=1.0,
        min_chunk_seconds=10.0,
    )


class TestAppControllerCancel:
    def test_cancel_shuts_down_root(self, app_controller):
        app_controller._root = MagicMock()

        app_controller._on_cancel()

        app_controller._root.quit.assert_called_once()

    def test_cancel_does_not_sys_exit(self, app_controller):
        """Cancel should not raise SystemExit — exits naturally via mainloop."""
        app_controller._root = MagicMock()

        app_controller._on_cancel()  # should not raise

    def test_cancel_does_not_emit_markers(self, app_controller, capsys):
        """Protocol markers are emitted by GUI layer, not AppController."""
        app_controller._root = MagicMock()

        app_controller._on_cancel()

        captured = capsys.readouterr()
        assert "[CANCEL]" not in captured.out


class TestAppControllerDone:
    def test_done_emits_transcript(self, app_controller, capsys):
        app_controller._root = MagicMock()

        app_controller._on_done("hello world")

        captured = capsys.readouterr()
        assert f"[BEGIN version={__version__}]" in captured.out
        assert "hello world" in captured.out
        assert "[END]" in captured.out

    def test_done_empty_transcript(self, app_controller, capsys):
        app_controller._root = MagicMock()

        app_controller._on_done("")

        captured = capsys.readouterr()
        assert f"[BEGIN version={__version__}]" in captured.out
        assert "[END]" in captured.out

    def test_done_shuts_down_root(self, app_controller):
        app_controller._root = MagicMock()

        app_controller._on_done("text")

        app_controller._root.quit.assert_called_once()


class TestAppControllerError:
    def test_error_exits_with_error_code(self, app_controller):
        with pytest.raises(SystemExit) as exc_info:
            app_controller._on_error("something broke")

        assert exc_info.value.code == 1

    def test_error_does_not_emit_markers(self, app_controller, capsys):
        with pytest.raises(SystemExit):
            app_controller._on_error("something broke")

        captured = capsys.readouterr()
        assert "[BEGIN" not in captured.out
        assert "[CANCEL]" not in captured.out
