# Generated By: Claude Code (claude-opus-5)
"""Tests for capture-rate fallback and resampling in local_transcribe.recording."""

import numpy as np
from unittest.mock import MagicMock, patch

from local_transcribe.transcription import SAMPLE_RATE
from local_transcribe.recording import RecordingSession


def _mock_sd(*, accepts_16k, default_rate=48000):
    """Mock sounddevice where the device does or does not accept SAMPLE_RATE."""
    sd = MagicMock()
    if not accepts_16k:
        sd.check_input_settings.side_effect = ValueError("Invalid sample rate")
    sd.query_devices.return_value = {"default_samplerate": default_rate}
    return sd


def _session(sd):
    with patch("local_transcribe.recording._sd", return_value=sd):
        return RecordingSession(device_id=0)


class TestPickCaptureRate:
    def test_uses_sample_rate_when_device_accepts_it(self):
        sd = _mock_sd(accepts_16k=True)
        session = _session(sd)
        with patch("local_transcribe.recording._sd", return_value=sd):
            session.start()
        assert session._capture_rate == SAMPLE_RATE
        assert session._resampler is None
        assert sd.InputStream.call_args.kwargs["samplerate"] == SAMPLE_RATE

    def test_falls_back_to_device_default_rate(self):
        sd = _mock_sd(accepts_16k=False, default_rate=44100)
        session = _session(sd)
        with patch("local_transcribe.recording._sd", return_value=sd):
            session.start()
        assert session._capture_rate == 44100
        assert session._resampler is not None
        assert sd.InputStream.call_args.kwargs["samplerate"] == 44100


class TestResampledCapture:
    def test_one_second_at_48k_yields_one_second_at_16k(self):
        sd = _mock_sd(accepts_16k=False, default_rate=48000)
        session = _session(sd)
        with patch("local_transcribe.recording._sd", return_value=sd):
            session.start()
            session._recording = True

            # 1s of 440Hz tone at 48kHz, delivered in 100ms blocks.
            t = np.arange(48000) / 48000
            tone = (np.sin(2 * np.pi * 440 * t) * 10000).astype(np.int16)
            for i in range(0, len(tone), 4800):
                block = tone[i : i + 4800].reshape(-1, 1)
                session._audio_callback(block, len(block), None, None)

            audio = session.stop()

        # Whisper needs exactly SAMPLE_RATE. Allow a few samples of
        # resampler latency, not a 3x rate error.
        assert abs(len(audio) - SAMPLE_RATE) < 100
        assert audio.dtype == np.int16
        assert audio.shape[1] == 1
        # Signal survived, not silence.
        assert int(np.max(np.abs(audio))) > 5000

    def test_no_resampling_when_rate_matches(self):
        sd = _mock_sd(accepts_16k=True)
        session = _session(sd)
        with patch("local_transcribe.recording._sd", return_value=sd):
            session.start()
            session._recording = True
            block = np.full((1600, 1), 1000, dtype=np.int16)
            for _ in range(10):
                session._audio_callback(block, len(block), None, None)
            audio = session.stop()

        assert len(audio) == SAMPLE_RATE
