# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe_ui.protocol module."""

from local_transcribe_ui import __version__
from local_transcribe_ui.protocol import emit_begin, emit_cancel, emit_end


class TestProtocol:
    def test_emit_begin(self, capsys):
        emit_begin()
        captured = capsys.readouterr()
        assert captured.out == f"[BEGIN version={__version__}]\n"

    def test_emit_begin_flush(self, capsys):
        emit_begin(flush=True)
        captured = capsys.readouterr()
        assert f"[BEGIN version={__version__}]" in captured.out

    def test_emit_end(self, capsys):
        emit_end()
        captured = capsys.readouterr()
        assert captured.out == "[END]\n"

    def test_emit_cancel(self, capsys):
        emit_cancel()
        captured = capsys.readouterr()
        assert captured.out == "[CANCEL]\n"
