# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for RecordingController lifecycle."""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from local_transcribe_ui.recording_controller import RecordingController


@pytest.fixture
def mock_tk_root():
    """A mock tk.Tk root."""
    root = MagicMock()
    root.after = MagicMock(return_value="after_id")
    root.after_cancel = MagicMock()
    return root


@pytest.fixture
def mock_dependencies():
    """Patch engine dependencies so RecordingController can be instantiated."""
    mock_session = MagicMock()
    mock_session.is_recording = True
    mock_session._device_id = 0
    mock_session.stop.return_value = None

    mock_chunk_mgr = MagicMock()
    mock_chunk_mgr.get_transcript.return_value = "hello world"

    mock_window = MagicMock()

    with (
        patch(
            "local_transcribe_ui.recording_controller.start_whisper_preload"
        ) as mock_preload,
        patch(
            "local_transcribe_ui.recording_controller.ChunkManager",
            return_value=mock_chunk_mgr,
        ),
        patch(
            "local_transcribe_ui.recording_controller.SilenceDetector",
        ),
        patch(
            "local_transcribe_ui.recording_controller.RecordingSession",
            return_value=mock_session,
        ),
        patch(
            "local_transcribe_ui.recording_controller.RecordingWindow",
            return_value=mock_window,
        ),
        patch(
            "local_transcribe_ui.recording_controller.load_settings",
            return_value=MagicMock(),
        ),
    ):
        yield {
            "preload": mock_preload,
            "session": mock_session,
            "chunk_manager": mock_chunk_mgr,
            "window": mock_window,
        }


class TestRecordingControllerStart:
    def test_start_creates_components(self, mock_tk_root, mock_dependencies):
        controller = RecordingController(mock_tk_root)
        controller.start()

        mock_dependencies["preload"].assert_called_once()
        mock_dependencies["session"].start.assert_called_once()
        mock_dependencies["window"].show.assert_called_once()

    def test_start_calls_on_error_on_recording_error(self, mock_tk_root):
        from local_transcribe.recording import RecordingError

        on_error = MagicMock()

        with (
            patch("local_transcribe_ui.recording_controller.start_whisper_preload"),
            patch(
                "local_transcribe_ui.recording_controller.ChunkManager",
            ),
            patch(
                "local_transcribe_ui.recording_controller.SilenceDetector",
            ),
            patch(
                "local_transcribe_ui.recording_controller.RecordingSession",
                side_effect=RecordingError("no mic"),
            ),
            patch(
                "local_transcribe_ui.recording_controller.load_settings",
                return_value=MagicMock(),
            ),
        ):
            controller = RecordingController(mock_tk_root, on_error=on_error)
            controller.start()

        on_error.assert_called_once_with("no mic")

    def test_start_sets_stream_callback(self, mock_tk_root, mock_dependencies):
        on_chunk = MagicMock()
        controller = RecordingController(mock_tk_root, on_stream_chunk=on_chunk)
        controller.start()

        mock_dependencies["chunk_manager"].set_stream_callback.assert_called_once_with(
            on_chunk
        )


class TestRecordingControllerDone:
    def test_on_done_callback_receives_transcript(
        self, mock_tk_root, mock_dependencies
    ):
        on_done = MagicMock()
        controller = RecordingController(mock_tk_root, on_done=on_done)
        controller.start()

        controller.on_recording_done()

        on_done.assert_called_once_with("hello world")

    def test_on_done_destroys_window(self, mock_tk_root, mock_dependencies):
        controller = RecordingController(mock_tk_root)
        controller.start()

        controller.on_recording_done()

        mock_dependencies["window"].destroy.assert_called_once()

    def test_on_done_saves_wav(self, mock_tk_root, mock_dependencies):
        mock_dependencies["session"].stop.return_value = b"audio_data"

        with patch("local_transcribe_ui.recording_controller.save_wav_to") as mock_save:
            controller = RecordingController(mock_tk_root, wav_output="/tmp/test.wav")
            controller.start()
            controller.on_recording_done()

            mock_save.assert_called_once()


class TestRecordingControllerCancel:
    def test_on_cancel_callback_fires(self, mock_tk_root, mock_dependencies):
        on_cancel = MagicMock()
        controller = RecordingController(mock_tk_root, on_cancel=on_cancel)
        controller.start()

        controller.on_recording_cancelled()

        on_cancel.assert_called_once()

    def test_on_cancel_aborts_session(self, mock_tk_root, mock_dependencies):
        controller = RecordingController(mock_tk_root)
        controller.start()

        controller.on_recording_cancelled()

        mock_dependencies["session"].abort.assert_called_once()

    def test_on_cancel_destroys_window(self, mock_tk_root, mock_dependencies):
        controller = RecordingController(mock_tk_root)
        controller.start()

        controller.on_recording_cancelled()

        mock_dependencies["window"].destroy.assert_called_once()


class TestRecordingControllerIsActive:
    def test_is_active_before_start(self, mock_tk_root):
        with patch(
            "local_transcribe_ui.recording_controller.load_settings",
            return_value=MagicMock(),
        ):
            controller = RecordingController(mock_tk_root)
            assert not controller.is_active

    def test_is_active_after_start(self, mock_tk_root, mock_dependencies):
        controller = RecordingController(mock_tk_root)
        controller.start()
        assert controller.is_active
