# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe.recording module."""

import numpy as np
import pytest
from unittest.mock import patch

from local_transcribe.recording import RecordingError, RecordingSession


class TestRecordingSessionInit:
    def test_creates_with_explicit_device(self):
        with patch("local_transcribe.recording._sd"):
            session = RecordingSession(device_id=0)
            assert session._device_id == 0
            assert session.chunks == []
            assert session.is_recording is False
            assert session.is_paused is False
            assert session.level == 0.0

    def test_calls_get_default_when_no_device(self):
        with patch(
            "local_transcribe.recording.get_default_input_device", return_value=3
        ) as mock_default:
            session = RecordingSession()
            mock_default.assert_called_once()
            assert session._device_id == 3

    def test_binds_chunk_manager(self):
        from local_transcribe.chunking import ChunkManager

        mgr = ChunkManager(model_size="tiny")
        session = RecordingSession(device_id=0, chunk_manager=mgr)
        assert mgr._chunks_ref is session.chunks


class TestRecordingSessionOperations:
    def test_stop_with_no_audio_raises(self, mock_recording_session):
        mock_recording_session._recording = True
        with pytest.raises(RecordingError, match="No audio captured"):
            mock_recording_session.stop()

    def test_stop_concatenates_chunks(self, mock_recording_session):
        mock_recording_session._chunks = [
            np.ones((100, 1), dtype=np.int16),
            np.ones((200, 1), dtype=np.int16) * 2,
        ]
        mock_recording_session._recording = True

        audio = mock_recording_session.stop()
        assert len(audio) == 300
        assert audio[0, 0] == 1
        assert audio[100, 0] == 2

    def test_pause_resume(self, mock_recording_session):
        mock_recording_session._recording = True

        mock_recording_session.pause()
        assert mock_recording_session.is_paused is True
        assert mock_recording_session.is_recording is False

        mock_recording_session.resume()
        assert mock_recording_session.is_paused is False

    def test_abort_clears_stream(self, mock_recording_session):
        mock_recording_session._recording = True
        mock_recording_session.abort()
        assert mock_recording_session._recording is False

    def test_consume_silence_flush_boundary(self, mock_recording_session):
        mock_recording_session._silence_flush_boundary = 42
        assert mock_recording_session.consume_silence_flush_boundary() == 42
        assert mock_recording_session.consume_silence_flush_boundary() is None


class TestAudioCallback:
    def test_appends_chunk_and_computes_level(self, mock_recording_session):
        mock_recording_session._recording = True
        indata = np.full((160, 1), 5000, dtype=np.int16)

        mock_recording_session._audio_callback(indata, 160, None, None)

        assert len(mock_recording_session.chunks) == 1
        assert mock_recording_session.level > 0.0

    def test_ignores_when_paused(self, mock_recording_session):
        mock_recording_session._recording = True
        mock_recording_session._paused = True
        indata = np.full((160, 1), 5000, dtype=np.int16)

        mock_recording_session._audio_callback(indata, 160, None, None)

        assert len(mock_recording_session.chunks) == 0
        assert mock_recording_session.level == 0.0

    def test_feeds_silence_detector(self, mock_recording_session):
        from local_transcribe.chunking import ChunkManager, SilenceDetector

        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.01,
            min_chunk_s=0.0,
            buffer_s=0.0,
            callback_interval_s=0.01,
        )
        mgr = ChunkManager(model_size="tiny")
        mgr.bind_chunks(mock_recording_session._chunks)

        mock_recording_session._silence_detector = det
        mock_recording_session._chunk_manager = mgr
        mock_recording_session._recording = True

        # Feed enough silent callbacks to trigger
        silent_data = np.zeros((160, 1), dtype=np.int16)
        for _ in range(20):
            mock_recording_session._audio_callback(silent_data, 160, None, None)

        # The silence detector should have set a boundary
        boundary = mock_recording_session.consume_silence_flush_boundary()
        assert boundary is not None


class TestElapsedSeconds:
    def test_returns_zero_when_not_recording(self, mock_recording_session):
        assert mock_recording_session.elapsed_seconds() == 0.0

    def test_returns_positive_when_recording(self, mock_recording_session):
        import time

        mock_recording_session._recording = True
        mock_recording_session._start_time = time.time() - 5.0
        elapsed = mock_recording_session.elapsed_seconds()
        assert 4.9 < elapsed < 5.5
