# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe_ui.protocol module."""

import pytest

from local_transcribe_ui import __version__
from local_transcribe_ui.protocol import emit_begin, emit_end


class TestProtocol:
    def test_emit_begin(self, capsys):
        emit_begin()
        captured = capsys.readouterr()
        assert captured.out == f"[BEGIN version={__version__}]\n"

    def test_emit_begin_flush(self, capsys):
        emit_begin(flush=True)
        captured = capsys.readouterr()
        assert f"[BEGIN version={__version__}]" in captured.out

    def test_emit_end(self, capsys):
        emit_end()
        captured = capsys.readouterr()
        assert captured.out == "[END]\n"

    @pytest.mark.requires_subprocess
    def test_emit_cancel(self, tmp_path):
        """emit_cancel uses os.write(1) to bypass Python buffering."""
        import subprocess
        import sys

        script = tmp_path / "test_cancel.py"
        script.write_text(
            "from local_transcribe_ui.protocol import emit_cancel\nemit_cancel()\n"
        )
        result = subprocess.run(
            [sys.executable, str(script)],
            capture_output=True,
            text=True,
        )
        assert result.stdout == "[CANCEL]\n"
