# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for local_transcribe.chunking module."""

import numpy as np
from unittest.mock import patch

from local_transcribe.chunking import (
    ChunkManager,
    SilenceDetector,
    trim_silence,
)
from local_transcribe.transcription import SAMPLE_RATE


class TestSilenceDetector:
    def test_no_trigger_on_speech(self):
        det = SilenceDetector(threshold=0.08, duration_s=2.0, min_chunk_s=0.0)
        for i in range(500):
            result = det.feed(0.5, i, float(i) * 0.01)
            assert result is None

    def test_triggers_on_sustained_silence(self):
        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.1,
            min_chunk_s=0.0,
            buffer_s=0.0,
            callback_interval_s=0.01,
        )
        triggered = False
        for i in range(100):
            result = det.feed(0.01, i, float(i) * 0.01)
            if result is not None:
                triggered = True
                break
        assert triggered

    def test_no_trigger_below_min_chunk(self):
        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.1,
            min_chunk_s=100.0,
            buffer_s=0.0,
            callback_interval_s=0.01,
        )
        for i in range(500):
            result = det.feed(0.01, i, float(i) * 0.01)
            assert result is None

    def test_reset_allows_retrigger(self):
        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.05,
            min_chunk_s=0.0,
            buffer_s=0.0,
            callback_interval_s=0.01,
        )
        # Build up silence until trigger
        for i in range(50):
            det.feed(0.01, i, float(i) * 0.01)
        det.reset()
        # After reset, should be able to trigger again with fresh silence
        triggered = False
        for i in range(50, 100):
            result = det.feed(0.01, i, float(i) * 0.01)
            if result is not None:
                triggered = True
                break
        assert triggered

    def test_only_triggers_once(self):
        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.05,
            min_chunk_s=0.0,
            buffer_s=0.0,
            callback_interval_s=0.01,
        )
        triggers = []
        for i in range(200):
            result = det.feed(0.01, i, float(i) * 0.01)
            if result is not None:
                triggers.append(result)
        assert len(triggers) == 1

    def test_retriggers_after_speech(self):
        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.05,
            min_chunk_s=0.0,
            buffer_s=0.0,
            callback_interval_s=0.01,
        )
        triggers = []
        for i in range(50):
            result = det.feed(0.01, i, float(i) * 0.01)
            if result is not None:
                triggers.append(result)
        for i in range(50, 60):
            det.feed(0.5, i, float(i) * 0.01)
        for i in range(60, 120):
            result = det.feed(0.01, i, float(i) * 0.01)
            if result is not None:
                triggers.append(result)
        assert len(triggers) == 2

    def test_buffer_offsets_boundary(self):
        det = SilenceDetector(
            threshold=0.08,
            duration_s=0.05,
            min_chunk_s=0.0,
            buffer_s=0.1,
            callback_interval_s=0.01,
        )
        boundary = None
        for i in range(200):
            result = det.feed(0.01, i, float(i) * 0.01)
            if result is not None:
                boundary = result
                break
        assert boundary is not None
        assert boundary == 0 + 10  # onset at 0, buffer of 0.1s/0.01s = 10


class TestTrimSilence:
    def test_all_silence_returns_none(self, silence_audio):
        result = trim_silence(silence_audio, sample_rate=SAMPLE_RATE)
        assert result is None

    def test_preserves_speech(self):
        audio = np.zeros(SAMPLE_RATE * 3, dtype=np.int16)
        start = SAMPLE_RATE
        end = SAMPLE_RATE * 2
        audio[start:end] = 10000
        result = trim_silence(audio, sample_rate=SAMPLE_RATE)
        assert result is not None
        assert len(result) < len(audio)
        assert np.max(np.abs(result)) >= 10000

    def test_buffer_includes_padding(self):
        audio = np.zeros(SAMPLE_RATE * 3, dtype=np.int16)
        audio[SAMPLE_RATE : SAMPLE_RATE + 400] = 10000
        result = trim_silence(audio, sample_rate=SAMPLE_RATE, buffer_s=0.5)
        assert result is not None
        buffer_samples = int(0.5 * SAMPLE_RATE)
        assert len(result) >= 400 + buffer_samples

    def test_all_speech_returns_full_audio(self, speech_audio):
        result = trim_silence(speech_audio, sample_rate=SAMPLE_RATE)
        assert result is not None
        assert len(result) == len(speech_audio)


class TestChunkManager:
    def test_bind_and_flush(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=SAMPLE_RATE)
        chunks = [np.zeros(100, dtype=np.int16) for _ in range(5)]
        mgr.bind_chunks(chunks)
        assert mgr.boundary == 0

        flushed = mgr.flush(boundary=3)
        assert flushed is True
        assert mgr.boundary == 3

        # Verify enqueued audio shape
        item = mgr._queue.get_nowait()
        assert len(item) == 300

    def test_flush_nothing_returns_false(self):
        mgr = ChunkManager()
        chunks = []
        mgr.bind_chunks(chunks)
        assert mgr.flush() is False

    def test_flush_without_bind_returns_false(self):
        mgr = ChunkManager()
        assert mgr.flush() is False

    def test_queued_fraction(self):
        mgr = ChunkManager(sample_rate=SAMPLE_RATE)
        chunks = [np.zeros(100, dtype=np.int16) for _ in range(10)]
        mgr.bind_chunks(chunks)
        mgr.flush(boundary=5)
        fraction = mgr.queued_fraction()
        assert 0.49 < fraction < 0.51

    def test_progress_fraction_starts_zero(self):
        mgr = ChunkManager()
        chunks = [np.zeros(100, dtype=np.int16)]
        mgr.bind_chunks(chunks)
        assert mgr.progress_fraction() == 0.0

    def test_get_transcript_empty(self):
        mgr = ChunkManager()
        assert mgr.get_transcript() == ""

    def test_is_done_initially_false(self):
        mgr = ChunkManager()
        assert mgr.is_done() is False

    def test_finish_without_worker_sets_done(self):
        mgr = ChunkManager()
        chunks = []
        mgr.bind_chunks(chunks)
        mgr.finish()
        assert mgr.is_done() is True


class TestChunkManagerWorker:
    """Tests for the worker loop with mocked transcription."""

    def test_worker_transcribes_and_collects(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=SAMPLE_RATE)
        # Loud audio so trim_silence doesn't skip it
        chunks = [np.full(SAMPLE_RATE, 10000, dtype=np.int16)]
        mgr.bind_chunks(chunks)

        with patch("local_transcribe.chunking.transcribe_audio", return_value="hello"):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5.0)

        assert mgr.is_done()
        assert mgr.get_transcript() == "hello"
        assert mgr.progress_fraction() > 0.0

    def test_worker_skips_silence(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=SAMPLE_RATE)
        chunks = [np.zeros(SAMPLE_RATE, dtype=np.int16)]
        mgr.bind_chunks(chunks)

        with patch("local_transcribe.chunking.transcribe_audio") as mock_transcribe:
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5.0)

        assert mgr.is_done()
        assert mgr.get_transcript() == ""
        mock_transcribe.assert_not_called()

    def test_worker_calls_stream_callback(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=SAMPLE_RATE)
        chunks = [np.full(SAMPLE_RATE, 10000, dtype=np.int16)]
        mgr.bind_chunks(chunks)
        streamed = []
        mgr.set_stream_callback(lambda t: streamed.append(t))

        with patch(
            "local_transcribe.chunking.transcribe_audio", return_value="streamed text"
        ):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5.0)

        assert streamed == ["streamed text"]

    def test_worker_handles_transcription_error(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=SAMPLE_RATE)
        chunks = [np.full(SAMPLE_RATE, 10000, dtype=np.int16)]
        mgr.bind_chunks(chunks)

        with patch(
            "local_transcribe.chunking.transcribe_audio",
            side_effect=RuntimeError("model failed"),
        ):
            mgr.start_worker()
            mgr.flush()
            mgr.finish(timeout=5.0)

        assert mgr.is_done()
        assert len(mgr._errors) == 1
        assert mgr.get_transcript() == ""

    def test_worker_multiple_chunks(self):
        mgr = ChunkManager(model_size="tiny", sample_rate=SAMPLE_RATE)
        chunks = [
            np.full(SAMPLE_RATE, 10000, dtype=np.int16),
            np.full(SAMPLE_RATE, 10000, dtype=np.int16),
        ]
        mgr.bind_chunks(chunks)

        with patch(
            "local_transcribe.chunking.transcribe_audio",
            side_effect=["first chunk", "second chunk"],
        ):
            mgr.start_worker()
            mgr.flush(boundary=1)
            mgr.flush(boundary=2)
            mgr.finish(timeout=5.0)

        assert mgr.get_transcript() == "first chunk second chunk"
