#!/usr/bin/env bash
# Generated By: Claude Code (claude-opus-5)
#
# Bump the semver in pyproject.toml and every version file, in place.
# Usage: version-bump.sh <major|minor|patch> [VERSION_FILES...]

set -euo pipefail

PART="${1:-}"
shift || true

case "$PART" in
    major | minor | patch) ;;
    *)
        echo "version-bump: FAIL — expected major, minor, or patch, got '${PART}'" >&2
        exit 1
        ;;
esac

current=$(grep -m1 '^version\s*=' pyproject.toml | sed 's/.*"\(.*\)".*/\1/')

# Prereleases and build metadata have no single obvious successor, so refuse
# rather than guess. Edit by hand, then bump from a plain release version.
if ! echo "$current" | grep -Pq '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'; then
    echo "version-bump: FAIL — pyproject.toml version '$current' is not a plain MAJOR.MINOR.PATCH" >&2
    exit 1
fi

IFS=. read -r major minor patch <<<"$current"

case "$PART" in
    major)
        major=$((major + 1))
        minor=0
        patch=0
        ;;
    minor)
        minor=$((minor + 1))
        patch=0
        ;;
    patch) patch=$((patch + 1)) ;;
esac

new="${major}.${minor}.${patch}"

# Every file is checked before anything is written — a missing version file
# must not leave pyproject.toml bumped and the packages behind.
for f in "$@"; do
    if [ ! -f "$f" ]; then
        echo "version-bump: FAIL — no such version file: $f" >&2
        exit 1
    fi
    if ! grep -q '__version__' "$f"; then
        echo "version-bump: FAIL — no __version__ in $f" >&2
        exit 1
    fi
done

sed -i "0,/^version\s*=.*/s//version = \"${new}\"/" pyproject.toml
for f in "$@"; do
    sed -i "0,/^__version__\s*=.*/s//__version__ = \"${new}\"/" "$f"
done

echo "version-bump: $current -> $new (pyproject.toml${*:+ $*})"
