#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Validate semantic versioning: format, sources match, version bumped vs mainline.
# Usage: version-check.sh [VERSION_FILE] [VERSION_DIRS...]

set -euo pipefail

VERSION_FILE="${1:-}"
shift || true
VERSION_DIRS="$*"

# Official semver.org regex
SEMVER_RE='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'

toml_ver=$(grep -m1 '^version\s*=' pyproject.toml | sed 's/.*"\(.*\)".*/\1/')

if ! echo "$toml_ver" | grep -Pq "$SEMVER_RE"; then
    echo "version-check: FAIL — pyproject.toml version '$toml_ver' is not valid semver (see https://semver.org)" >&2
    exit 1
fi

# VERSION_FILE may name several files (word-split intentionally). Each package
# that declares __version__ must be listed, or it drifts from pyproject.toml
# unchecked — and __version__ is what `--version` and the [BEGIN] marker print.
# shellcheck disable=SC2086
for version_file in $VERSION_FILE; do
    [ -f "$version_file" ] || continue
    code_ver=$(grep -m1 '__version__' "$version_file" | sed 's/.*"\(.*\)".*/\1/')
    if [ "$toml_ver" != "$code_ver" ]; then
        echo "version-check: FAIL — pyproject.toml has '$toml_ver' but $version_file has '$code_ver'" >&2
        exit 1
    fi
done

# Find mainline branch
mainline=""
if git rev-parse --verify main >/dev/null 2>&1; then
    mainline=main
elif git rev-parse --verify origin/main >/dev/null 2>&1; then
    mainline=origin/main
elif git rev-parse --verify master >/dev/null 2>&1; then
    mainline=master
elif git rev-parse --verify origin/master >/dev/null 2>&1; then
    mainline=origin/master
fi

if [ -z "$mainline" ]; then
    echo "version-check: PASS — $toml_ver (no mainline branch found, bump check skipped)"
    exit 0
fi

base=$(git merge-base HEAD "$mainline" 2>/dev/null || true)

if [ -z "$base" ]; then
    echo "version-check: PASS — $toml_ver (no common ancestor with $mainline)"
    exit 0
fi

# If VERSION_DIRS is set, only require bump when source files changed
if [ -n "$VERSION_DIRS" ]; then
    # shellcheck disable=SC2086
    source_changes=$(git diff --name-only "$base" HEAD -- $VERSION_DIRS)
    if [ -z "$source_changes" ]; then
        echo "version-check: PASS — $toml_ver (no source changes in: $VERSION_DIRS)"
        exit 0
    fi
fi

base_ver=$(git show "$base:pyproject.toml" 2>/dev/null | grep -m1 '^version\s*=' | sed 's/.*"\(.*\)".*/\1/' || true)

if [ -n "$base_ver" ] && [ "$toml_ver" = "$base_ver" ]; then
    echo "version-check: FAIL — version not bumped: both current and $mainline have '$toml_ver'" >&2
    exit 1
fi

echo "version-check: PASS — ${base_ver:-new} -> $toml_ver"
