# Generated By: Claude Code (claude-opus-5)

.PHONY: version-bump-major version-bump-minor version-bump-patch

version-bump-major:  ## Bump MAJOR version in pyproject.toml and both package __init__.py files
	@bash scripts/version-bump.sh major $(VERSION_FILE)

version-bump-minor:  ## Bump MINOR version in pyproject.toml and both package __init__.py files
	@bash scripts/version-bump.sh minor $(VERSION_FILE)

version-bump-patch:  ## Bump PATCH version in pyproject.toml and both package __init__.py files
	@bash scripts/version-bump.sh patch $(VERSION_FILE)
