# Generated By: Claude Code (Claude Opus 4.6)
"""local-transcribe-ui: Tkinter GUI and CLI frontend for local-transcribe."""

__version__ = "0.6.1"

from local_transcribe_ui.recording_controller import RecordingController

__all__ = ["RecordingController"]
