# Generated By: Claude Code (Claude Opus 4.6)
"""Entry point for local-transcribe.

Subcommands:
    record      Record from microphone with GUI (default)
    transcribe  Transcribe an existing WAV file (CLI-only)
    devices     List available audio input devices
"""

import argparse
import logging
import os
import sys

from local_transcribe_ui import __version__
from local_transcribe_ui.config import setup_logging


def _add_debug_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--debug",
        nargs="?",
        const=True,
        default=False,
        metavar="LOGFILE",
        help="Enable debug logging. Optionally specify a file path.",
    )


def _cmd_record(args: argparse.Namespace) -> None:
    """Record from microphone with tkinter GUI."""
    setup_logging(args.debug)
    logger = logging.getLogger(__name__)
    logger.info("local-transcribe %s", __version__)

    # Windows DPI awareness — must be before Tk() is created
    if sys.platform == "win32":
        try:
            import ctypes

            ctypes.windll.shcore.SetProcessDpiAwareness(1)
        except Exception:
            pass

    # Deferred import — only load tkinter/sounddevice when recording
    from local_transcribe_ui.controller import AppController

    app = AppController(
        model_size=args.model,
        device_id=args.device,
        stream_mode=args.stream,
        wav_output=args.wav_output,
    )
    app.run()


def _cmd_transcribe(args: argparse.Namespace) -> None:
    """Transcribe a WAV file — CLI-only, no GUI."""
    setup_logging(args.debug)
    logger = logging.getLogger(__name__)
    logger.info("local-transcribe %s", __version__)

    import time
    import wave

    from local_transcribe import start_whisper_preload, transcribe_wav
    from local_transcribe_ui.protocol import emit_begin, emit_end

    wav_path = args.file
    if not os.path.exists(wav_path):
        logger.error("WAV file not found: %s", wav_path)
        sys.exit(1)

    start_whisper_preload()
    t_start = time.time()
    transcript = transcribe_wav(wav_path, model_size=args.model)
    t_elapsed = time.time() - t_start

    try:
        with wave.open(wav_path, "rb") as wf:
            audio_duration = wf.getnframes() / wf.getframerate()
    except Exception:
        audio_duration = 0.0

    logger.info(
        "Transcribed %.1fs audio in %.1fs (model=%s)",
        audio_duration,
        t_elapsed,
        args.model,
    )
    emit_begin()
    print(transcript)
    emit_end()


def _cmd_devices(args: argparse.Namespace) -> None:
    """List available audio input devices."""
    setup_logging(args.debug)

    from local_transcribe.recording import get_input_devices

    devices = get_input_devices()
    if not devices:
        print("No input devices found.", file=sys.stderr)
        sys.exit(1)
    for dev in devices:
        print(f"  {dev['id']}: {dev['name']}")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="local-transcribe",
        description="Voice-to-text with local Whisper",
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}"
    )
    subparsers = parser.add_subparsers(dest="command")

    # record (default)
    record_parser = subparsers.add_parser(
        "record", help="Record from microphone with GUI"
    )
    record_parser.add_argument(
        "--model",
        type=str,
        default="small",
        choices=["tiny", "base", "small", "medium", "large"],
        help="Whisper model size (default: small)",
    )
    record_parser.add_argument(
        "--device",
        type=int,
        default=None,
        help="Audio input device ID",
    )
    record_parser.add_argument(
        "--wav-output",
        type=str,
        default=None,
        metavar="PATH",
        help="Save recorded audio to this WAV file",
    )
    record_parser.add_argument(
        "--stream",
        action="store_true",
        help="Stream transcript chunks to stdout as they complete",
    )
    _add_debug_arg(record_parser)
    record_parser.set_defaults(func=_cmd_record)

    # transcribe
    transcribe_parser = subparsers.add_parser(
        "transcribe", help="Transcribe an existing WAV file"
    )
    transcribe_parser.add_argument("file", type=str, help="Path to WAV file")
    transcribe_parser.add_argument(
        "--model",
        type=str,
        default="small",
        choices=["tiny", "base", "small", "medium", "large"],
        help="Whisper model size (default: small)",
    )
    _add_debug_arg(transcribe_parser)
    transcribe_parser.set_defaults(func=_cmd_transcribe)

    # devices
    devices_parser = subparsers.add_parser(
        "devices", help="List available audio input devices"
    )
    _add_debug_arg(devices_parser)
    devices_parser.set_defaults(func=_cmd_devices)

    args = parser.parse_args()

    if not hasattr(args, "func"):
        parser.print_help()
        sys.exit(1)

    args.func(args)


if __name__ == "__main__":
    main()
