# Generated By: Claude Code (Claude Opus 4.6)
"""Constants, defaults, and application configuration."""

import logging
import logging.handlers
import sys

# Application identity
APP_NAME = "local-transcribe"
SETTINGS_FILENAME = "settings.json"
LOCK_FILENAME = "voice.lock"

# Exit codes
EXIT_SUCCESS = 0
EXIT_ERROR = 1

# Display
MAX_PATH_DISPLAY_LENGTH = 60
TIMER_UPDATE_MS = 200
BUTTON_WIDTH = 7

# Colors — recording states
COLOR_RECORDING = "#cc0000"
COLOR_RECORDING_ACTIVE = "#990000"
COLOR_PAUSED = "#cc8800"
COLOR_PAUSED_ACTIVE = "#996600"
COLOR_DONE = "#228B22"
COLOR_DONE_ACTIVE = "#1a6b1a"
COLOR_MUTED = "#666666"
COLOR_TRANSCRIBING = "#4477cc"

# Fonts
FONT_STATUS = ("sans-serif", 16, "bold")
FONT_TIMER = ("monospace", 24)
FONT_DETAIL = ("monospace", 9)
FONT_BUTTON = ("sans-serif", 12)

# Level meter
LEVEL_BAR_WIDTH = 260
LEVEL_BAR_HEIGHT = 8
LEVEL_UPDATE_MS = 50
LEVEL_COLOR = "#888888"
LEVEL_BG_COLOR = "#d0d0d0"

# Chunk progress bar
CHUNK_PROGRESS_HEIGHT = 6
CHUNK_PROGRESS_QUEUED = "#ddaa44"
CHUNK_PROGRESS_DONE = COLOR_TRANSCRIBING
CHUNK_PROGRESS_BG = "#d0d0d0"
TRANSCRIBING_POLL_MS = 200

# Settings defaults
DEFAULT_WINDOW_X = None
DEFAULT_WINDOW_Y = None

# Logging
LOG_FORMAT = "%(asctime)s %(levelname)s %(name)s: %(message)s"
LOG_MODULES = ("local_transcribe", "local_transcribe_ui")


def setup_logging(
    *, debug: bool = False, quiet: bool = False, log_file: str | None = None
) -> None:
    """Configure logging for the application.

    Args:
        debug: Enable DEBUG-level logging. Overrides quiet.
        quiet: Suppress INFO-level output (WARNING and above only).
        log_file: Path to write logs to file via RotatingFileHandler.
    """
    import types
    from pathlib import Path

    if debug:
        log_level = logging.DEBUG
    elif quiet:
        log_level = logging.WARNING
    else:
        log_level = logging.INFO

    handler: logging.Handler
    if log_file:
        resolved = str(Path(log_file).expanduser().resolve())
        Path(resolved).parent.mkdir(parents=True, exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            resolved,
            maxBytes=2 * 1024 * 1024,
            backupCount=1,
            encoding="utf-8",
        )
    else:
        handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(logging.Formatter(LOG_FORMAT))

    for name in LOG_MODULES:
        mod_logger = logging.getLogger(name)
        mod_logger.addHandler(handler)
        mod_logger.setLevel(log_level)

    # Route uncaught exceptions through the logging system
    root_logger = logging.getLogger(LOG_MODULES[0])

    def _excepthook(
        exc_type: type[BaseException],
        exc_value: BaseException,
        exc_tb: types.TracebackType | None,
    ) -> None:
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_tb)
            return
        root_logger.critical(
            "uncaught exception", exc_info=(exc_type, exc_value, exc_tb)
        )

    sys.excepthook = _excepthook
