# Generated By: Claude Code (Claude Opus 4.6)
"""Constants, defaults, and application configuration."""

import logging
import os
import sys

# Application identity
APP_NAME = "local-transcribe"
SETTINGS_FILENAME = "settings.json"
LOCK_FILENAME = "voice.lock"

# Exit codes
EXIT_SUCCESS = 0
EXIT_ERROR = 1

# Display
MAX_PATH_DISPLAY_LENGTH = 60
TIMER_UPDATE_MS = 200
BUTTON_WIDTH = 7

# Colors — recording states
COLOR_RECORDING = "#cc0000"
COLOR_RECORDING_ACTIVE = "#990000"
COLOR_PAUSED = "#cc8800"
COLOR_PAUSED_ACTIVE = "#996600"
COLOR_DONE = "#228B22"
COLOR_DONE_ACTIVE = "#1a6b1a"
COLOR_MUTED = "#666666"
COLOR_TRANSCRIBING = "#4477cc"

# Fonts
FONT_STATUS = ("sans-serif", 16, "bold")
FONT_TIMER = ("monospace", 24)
FONT_DETAIL = ("monospace", 9)
FONT_BUTTON = ("sans-serif", 12)

# Level meter
LEVEL_BAR_WIDTH = 260
LEVEL_BAR_HEIGHT = 8
LEVEL_UPDATE_MS = 50
LEVEL_COLOR = "#888888"
LEVEL_BG_COLOR = "#d0d0d0"

# Chunk progress bar
CHUNK_PROGRESS_HEIGHT = 6
CHUNK_PROGRESS_QUEUED = "#ddaa44"
CHUNK_PROGRESS_DONE = COLOR_TRANSCRIBING
CHUNK_PROGRESS_BG = "#d0d0d0"
TRANSCRIBING_POLL_MS = 200

# Settings defaults
DEFAULT_WINDOW_X = None
DEFAULT_WINDOW_Y = None

# Logging
LOG_FORMAT = "%(asctime)s %(levelname)s %(name)s: %(message)s"
LOG_MODULES = ("local_transcribe", "local_transcribe_ui")


def setup_logging(debug: object = False) -> None:
    """Configure logging for the application.

    Args:
        debug: False for INFO level. True for DEBUG to stderr.
            A string path for DEBUG to a file (directory created if needed).
    """
    log_level = logging.DEBUG if debug else logging.INFO
    handler: logging.Handler
    if debug and debug is not True:
        log_path = os.path.abspath(os.path.expanduser(str(debug)))
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        handler = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    else:
        handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(logging.Formatter(LOG_FORMAT))
    for name in LOG_MODULES:
        mod_logger = logging.getLogger(name)
        mod_logger.addHandler(handler)
        mod_logger.setLevel(log_level)
