# Generated By: Claude Code (Claude Opus 4.6)
"""Application controller — thin CLI wrapper around RecordingController.

Owns the tk.Tk root, mainloop, lockfile, and stdout protocol.
GUI-only — CLI operations (transcribe, devices) are handled by __main__.py.
"""

from __future__ import annotations

import json
import logging
import sys
import tkinter as tk

from local_transcribe_ui import config
from local_transcribe_ui.lock import LockAcquireError, acquire_lock, release_lock
from local_transcribe_ui.protocol import emit_begin, emit_cancel, emit_end
from local_transcribe_ui.recording_controller import RecordingController

logger = logging.getLogger(__name__)


class AppController:
    """CLI wrapper around RecordingController.

    Adds mainloop ownership, lockfile management, stdout protocol,
    and sys.exit() — everything that makes sense for standalone CLI
    use but not for embedding.

    Args:
        model_size: Whisper model size.
        device_id: Audio input device ID (None for default).
        stream_mode: Stream transcript chunks to stdout as they complete.
        wav_output: Optional path to save recorded audio.
        compute_device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
    """

    def __init__(
        self,
        *,
        model_size: str,
        device_id: int | None = None,
        stream_mode: bool = False,
        wav_output: str | None = None,
        compute_device: str,
        compute_type: str,
        silence_threshold: float,
        silence_duration: float,
        min_chunk_seconds: float,
        vad_filter: bool = True,
        condition_on_previous_text: bool = True,
        output_format: str = "plain",
    ):
        self._model_size = model_size
        self._device_id = device_id
        self._stream_mode = stream_mode
        self._wav_output = wav_output
        self._compute_device = compute_device
        self._compute_type = compute_type
        self._silence_threshold = silence_threshold
        self._silence_duration = silence_duration
        self._min_chunk_seconds = min_chunk_seconds
        self._vad_filter = vad_filter
        self._condition_on_previous_text = condition_on_previous_text
        self._output_format = output_format

        self._root: tk.Tk | None = None
        self._controller: RecordingController | None = None
        self._begun = False

    def run(self) -> None:
        """Run the GUI recording flow."""
        try:
            acquire_lock()
        except LockAcquireError as e:
            logger.error("%s", e)
            sys.exit(config.EXIT_ERROR)

        try:
            self._run_gui()
        finally:
            release_lock()

    def _run_gui(self) -> None:
        """Set up RecordingController, enter mainloop."""
        self._root = tk.Tk()
        self._root.withdraw()

        self._controller = RecordingController(
            self._root,
            model_size=self._model_size,
            device_id=self._device_id,
            on_done=self._on_done,
            on_cancel=self._on_cancel,
            on_error=self._on_error,
            on_stream_chunk=self._on_stream_chunk if self._stream_mode else None,
            wav_output=self._wav_output,
            compute_device=self._compute_device,
            compute_type=self._compute_type,
            silence_threshold=self._silence_threshold,
            silence_duration=self._silence_duration,
            min_chunk_seconds=self._min_chunk_seconds,
            vad_filter=self._vad_filter,
            condition_on_previous_text=self._condition_on_previous_text,
        )

        self._controller.start()
        self._root.mainloop()

    def _on_done(self, transcript: str) -> None:
        """Handle completed transcript — emit to stdout and quit."""
        use_json = self._output_format == "json"

        if not transcript:
            emit_begin()
            if use_json:
                print("[]")
            emit_end()
            logger.warning("No speech detected in audio.")
        elif self._stream_mode:
            emit_end()
        else:
            emit_begin()
            if use_json and self._controller:
                segments = self._controller.get_segments()
                print(json.dumps(segments, ensure_ascii=False, indent=2))
            else:
                print(transcript)
            emit_end()

        self._shutdown()

    def _on_cancel(self) -> None:
        """Handle cancellation — emit cancel marker and shut down GUI."""
        emit_cancel()
        self._shutdown()

    def _on_error(self, error: str) -> None:
        """Handle error — log and exit."""
        logger.error("%s", error)
        sys.exit(config.EXIT_ERROR)

    def _on_stream_chunk(self, text: str) -> None:
        """Callback for streaming transcript chunks."""
        if not self._begun:
            emit_begin(flush=True)
            self._begun = True
        print(text, flush=True)

    def _shutdown(self) -> None:
        """Clean shutdown of GUI."""
        if self._root:
            self._root.quit()
