# Generated By: Claude Code (Claude Opus 4.6)
"""Application controller — coordinates recording, transcription, and GUI.

Owns the hidden tk.Tk root and manages the full recording lifecycle.
GUI-only — CLI operations (transcribe, devices) are handled by __main__.py.
"""

from __future__ import annotations

import logging
import os
import sys
import tkinter as tk

from local_transcribe import (
    ChunkManager,
    RecordingSession,
    SilenceDetector,
    save_wav_to,
    start_whisper_preload,
)
from local_transcribe.recording import RecordingError
from local_transcribe_ui import config
from local_transcribe_ui.gui import RecordingWindow
from local_transcribe_ui.lock import LockAcquireError, acquire_lock, release_lock
from local_transcribe_ui.protocol import emit_begin, emit_cancel, emit_end
from local_transcribe_ui.settings import Settings, load_settings

logger = logging.getLogger(__name__)


class AppController:
    """Coordinates recording, transcription, and GUI lifecycle.

    Args:
        model_size: Whisper model size.
        device_id: Audio input device ID (None for default).
        stream_mode: Stream transcript chunks to stdout as they complete.
        wav_output: Optional path to save recorded audio.
    """

    def __init__(
        self,
        *,
        model_size: str = "small",
        device_id: int | None = None,
        stream_mode: bool = False,
        wav_output: str | None = None,
    ):
        self._model_size = model_size
        self._device_id = device_id
        self._stream_mode = stream_mode
        self._wav_output = wav_output

        self._settings: Settings = load_settings()
        self._session: RecordingSession | None = None
        self._chunk_manager: ChunkManager | None = None
        self._recording_window: RecordingWindow | None = None
        self._root: tk.Tk | None = None
        self._begun = False

    def run(self) -> None:
        """Run the GUI recording flow."""
        try:
            acquire_lock()
        except LockAcquireError as e:
            logger.error("%s", e)
            sys.exit(config.EXIT_ERROR)

        try:
            self._run_gui()
        finally:
            release_lock()

    def _run_gui(self) -> None:
        """Set up engine, build GUI, enter mainloop."""
        start_whisper_preload()

        self._chunk_manager = ChunkManager(model_size=self._model_size)
        silence_detector = SilenceDetector()

        if self._stream_mode:
            self._chunk_manager.set_stream_callback(self._on_stream_chunk)
        self._chunk_manager.start_worker()

        try:
            self._session = RecordingSession(
                device_id=self._device_id,
                chunk_manager=self._chunk_manager,
                silence_detector=silence_detector,
            )
        except RecordingError as e:
            logger.error("%s", e)
            sys.exit(config.EXIT_ERROR)

        self._root = tk.Tk()
        self._root.withdraw()

        self._recording_window = RecordingWindow(
            self._root,
            self,
            self._settings,
            self._session,
            self._chunk_manager,
        )

        # Get device name for display
        try:
            from local_transcribe.recording import _sd

            device_name = _sd().query_devices(self._session._device_id)["name"]
        except Exception:
            device_name = "Unknown"

        self._session.start()
        self._recording_window.show(cwd=os.getcwd(), device_name=device_name)

        self._root.mainloop()

    def on_recording_cancelled(self) -> None:
        """Called by RecordingWindow when user cancels."""
        assert self._session is not None
        self._session.abort()
        emit_cancel()
        self._shutdown()
        sys.exit(config.EXIT_SUCCESS)

    def on_recording_done(self) -> None:
        """Called by RecordingWindow when transcription completes."""
        assert self._session is not None
        assert self._chunk_manager is not None

        try:
            audio_data = self._session.stop()
        except RecordingError:
            audio_data = None

        if self._wav_output and audio_data is not None:
            wav_path = os.path.abspath(self._wav_output)
            save_wav_to(audio_data, wav_path)
            logger.info("Saved audio to %s", wav_path)

        transcript = self._chunk_manager.get_transcript()

        if not transcript:
            emit_begin()
            emit_end()
            logger.warning("No speech detected in audio.")
        elif self._stream_mode:
            emit_end()
        else:
            emit_begin()
            print(transcript)
            emit_end()

        self._shutdown()

    def _on_stream_chunk(self, text: str) -> None:
        """Callback for streaming transcript chunks."""
        if not self._begun:
            emit_begin(flush=True)
            self._begun = True
        print(text, flush=True)

    def _shutdown(self) -> None:
        """Clean shutdown of GUI."""
        if self._recording_window:
            self._recording_window.destroy()
        if self._root:
            self._root.quit()
