# Generated By: Claude Code (Claude Opus 4.6)
"""Recording window — tkinter GUI for voice recording with live transcription.

Composition over inheritance: RecordingWindow holds a Toplevel reference,
does not inherit from any tkinter class.
"""

from __future__ import annotations

import logging
import os
import tkinter as tk
from typing import TYPE_CHECKING

from local_transcribe.recording import RecordingSession
from local_transcribe.chunking import ChunkManager
from local_transcribe_ui import config
from local_transcribe_ui.protocol import emit_cancel
from local_transcribe_ui.settings import Settings, save_settings

if TYPE_CHECKING:
    from local_transcribe_ui.recording_controller import RecordingController

logger = logging.getLogger(__name__)


class RecordingCancelled(Exception):
    """Raised when the user cancels recording."""


def _home_relative_path(path: str) -> str:
    """Convert an absolute path to ~/relative form."""
    home = os.path.expanduser("~")
    if path == home or path.startswith(home + os.sep):
        return "~" + path[len(home) :]
    return path


def _truncate_path(
    path: str, *, max_length: int = config.MAX_PATH_DISPLAY_LENGTH
) -> str:
    if len(path) > max_length:
        return "..." + path[-(max_length - 3) :]
    return path


class RecordingWindow:
    """Tkinter recording popup with level meter and transcription progress.

    Uses composition — holds a Toplevel reference, not inheritance.

    Args:
        root: Hidden tk.Tk root for after() scheduling.
        controller: RecordingController for lifecycle callbacks.
        settings: Current settings (window position).
        session: Active RecordingSession from the engine.
        chunk_manager: ChunkManager for background transcription.
    """

    def __init__(
        self,
        root: tk.Tk,
        controller: RecordingController,
        settings: Settings,
        session: RecordingSession,
        chunk_manager: ChunkManager,
    ):
        self._root = root
        self._controller = controller
        self._settings = settings
        self._session = session
        self._chunk_manager = chunk_manager
        self._window: tk.Toplevel | None = None
        self._pending_after_ids: list[str] = []
        self._cancelled = False
        self._done = False

    def show(self, *, cwd: str, device_name: str) -> None:
        """Build and display the recording window."""
        win = tk.Toplevel(self._root)
        win.title("Voice Recording")
        win.attributes("-topmost", True)
        win.resizable(False, False)
        self._window = win

        if self._settings.window_x is not None and self._settings.window_y is not None:
            win.geometry(f"+{self._settings.window_x}+{self._settings.window_y}")

        frame = tk.Frame(win, padx=20, pady=15)
        frame.pack()

        # Status + timer row
        timer_frame = tk.Frame(frame)
        timer_frame.pack(pady=(10, 5))
        timer_frame.grid_columnconfigure(0, minsize=160)

        self._status_var = tk.StringVar(value="Recording:")
        self._status_label = tk.Label(
            timer_frame,
            textvariable=self._status_var,
            font=config.FONT_STATUS,
            fg=config.COLOR_RECORDING,
            width=11,
            anchor="w",
        )
        self._status_label.grid(row=0, column=0, sticky="w", padx=(0, 5))

        self._elapsed_var = tk.StringVar(value="0:00")
        tk.Label(
            timer_frame, textvariable=self._elapsed_var, font=config.FONT_STATUS
        ).grid(row=0, column=1, sticky="e")

        # Context labels
        display_cwd = _truncate_path(_home_relative_path(cwd))
        tk.Label(
            frame, text=display_cwd, font=config.FONT_DETAIL, fg=config.COLOR_MUTED
        ).pack()
        tk.Label(
            frame,
            text=f"Mic: {device_name}",
            font=config.FONT_DETAIL,
            fg=config.COLOR_MUTED,
        ).pack(pady=(0, 5))

        # Level meter
        self._level_canvas = tk.Canvas(
            frame,
            width=config.LEVEL_BAR_WIDTH,
            height=config.LEVEL_BAR_HEIGHT,
            bg=config.LEVEL_BG_COLOR,
            highlightthickness=0,
        )
        self._level_canvas.pack(pady=(0, 3))
        self._level_bar = self._level_canvas.create_rectangle(
            0, 0, 0, config.LEVEL_BAR_HEIGHT, fill=config.LEVEL_COLOR, width=0
        )

        # Chunk progress bar
        self._chunk_canvas = tk.Canvas(
            frame,
            width=config.LEVEL_BAR_WIDTH,
            height=config.CHUNK_PROGRESS_HEIGHT,
            bg=config.CHUNK_PROGRESS_BG,
            highlightthickness=0,
        )
        self._chunk_bar_queued = self._chunk_canvas.create_rectangle(
            0,
            0,
            0,
            config.CHUNK_PROGRESS_HEIGHT,
            fill=config.CHUNK_PROGRESS_QUEUED,
            width=0,
        )
        self._chunk_bar_done = self._chunk_canvas.create_rectangle(
            0,
            0,
            0,
            config.CHUNK_PROGRESS_HEIGHT,
            fill=config.CHUNK_PROGRESS_DONE,
            width=0,
        )
        self._chunk_canvas.pack(pady=(0, 10))

        # Buttons
        button_frame = tk.Frame(frame)
        button_frame.pack()

        self._cancel_btn = tk.Button(
            button_frame,
            text="Cancel",
            font=config.FONT_BUTTON,
            command=self._on_cancel,
            bg=config.COLOR_RECORDING,
            fg="white",
            activebackground=config.COLOR_RECORDING_ACTIVE,
            activeforeground="white",
            width=config.BUTTON_WIDTH,
            pady=5,
        )
        self._cancel_btn.pack(side=tk.LEFT, padx=(0, 5))

        self._pause_btn = tk.Button(
            button_frame,
            text="Pause",
            font=config.FONT_BUTTON,
            command=self._on_toggle_pause,
            bg=config.COLOR_PAUSED,
            fg="white",
            activebackground=config.COLOR_PAUSED_ACTIVE,
            activeforeground="white",
            width=config.BUTTON_WIDTH,
            pady=5,
        )
        self._pause_btn.pack(side=tk.LEFT, padx=(0, 5))

        self._done_btn = tk.Button(
            button_frame,
            text="Done",
            font=config.FONT_BUTTON,
            command=self._on_done,
            bg=config.COLOR_DONE,
            fg="white",
            activebackground=config.COLOR_DONE_ACTIVE,
            activeforeground="white",
            width=config.BUTTON_WIDTH,
            pady=5,
        )
        self._done_btn.pack(side=tk.LEFT)

        # Key bindings
        win.bind("<Escape>", lambda _e: self._on_cancel())
        win.bind("<space>", lambda _e: self._on_toggle_pause())
        win.bind("<Return>", lambda _e: self._on_done())
        win.protocol("WM_DELETE_WINDOW", self._on_cancel)

        # Start timers
        self._update_timer()
        self._update_level()

    @property
    def cancelled(self) -> bool:
        return self._cancelled

    @property
    def done(self) -> bool:
        return self._done

    def _cancel_pending_afters(self) -> None:
        for after_id in self._pending_after_ids:
            try:
                self._root.after_cancel(after_id)
            except Exception:
                pass
        self._pending_after_ids.clear()

    def _save_position(self) -> None:
        if not self._window or not self._window.winfo_exists():
            return
        try:
            self._settings.window_x = self._window.winfo_x()
            self._settings.window_y = self._window.winfo_y()
            save_settings(self._settings)
        except Exception:
            pass

    def _on_cancel(self) -> None:
        self._cancelled = True
        self._cancel_pending_afters()
        self._save_position()
        if self._window:
            self._window.destroy()
            self._window = None
        # Schedule cancel handling via root.after so protocol output
        # happens outside the tkinter event handler (same pattern as Done).
        self._root.after(0, self._finish_cancel)

    def _finish_cancel(self) -> None:
        emit_cancel()
        self._controller.on_recording_cancelled()

    def _on_toggle_pause(self) -> None:
        if self._session.is_paused:
            self._session.resume()
            self._status_var.set("Recording:")
            self._status_label.config(fg=config.COLOR_RECORDING)
            self._pause_btn.config(text="Pause")
            self._update_timer()
        else:
            self._session.pause()
            self._status_var.set("Paused:")
            self._status_label.config(fg=config.COLOR_PAUSED)
            self._pause_btn.config(text="Resume")

    def _on_done(self) -> None:
        self._done = True
        self._cancel_pending_afters()
        self._save_position()

        # Stop the audio stream so no new samples accumulate
        self._session.stop()

        # Flush and signal worker to stop
        self._chunk_manager.flush()
        self._chunk_manager.finish(timeout=0)

        # Transition to "Transcribing..." mode
        self._pause_btn.config(state=tk.DISABLED)
        self._done_btn.config(state=tk.DISABLED)
        self._status_var.set("Transcribing:")
        self._status_label.config(fg=config.COLOR_TRANSCRIBING)
        self._level_canvas.coords(self._level_bar, 0, 0, 0, config.LEVEL_BAR_HEIGHT)

        self._poll_transcription()

    def _poll_transcription(self) -> None:
        w = config.LEVEL_BAR_WIDTH
        h = config.CHUNK_PROGRESS_HEIGHT
        queued_w = int(self._chunk_manager.queued_fraction() * w)
        done_w = int(self._chunk_manager.progress_fraction() * w)
        self._chunk_canvas.coords(self._chunk_bar_queued, 0, 0, queued_w, h)
        self._chunk_canvas.coords(self._chunk_bar_done, 0, 0, done_w, h)

        if self._chunk_manager.is_done():
            if self._window:
                self._window.destroy()
                self._window = None
            self._controller.on_recording_done()
        else:
            after_id = self._root.after(
                config.TRANSCRIBING_POLL_MS, self._poll_transcription
            )
            self._pending_after_ids.append(after_id)

    def _update_timer(self) -> None:
        if not self._session.is_recording:
            return
        elapsed = int(self._session.elapsed_seconds())
        mins, secs = divmod(elapsed, 60)
        self._elapsed_var.set(f"{mins}:{secs:02d}")
        after_id = self._root.after(config.TIMER_UPDATE_MS, self._update_timer)
        self._pending_after_ids.append(after_id)

    def _update_level(self) -> None:
        if self._done or self._cancelled:
            return
        level = self._session.level if self._session.is_recording else 0.0
        bar_width = int(level * config.LEVEL_BAR_WIDTH)
        self._level_canvas.coords(
            self._level_bar, 0, 0, bar_width, config.LEVEL_BAR_HEIGHT
        )

        # Check silence-triggered flush
        boundary = self._session.consume_silence_flush_boundary()
        if boundary is not None:
            prev = self._chunk_manager.boundary
            self._chunk_manager.flush(boundary=boundary)
            logger.info(
                "silence flush: chunks %d-%d, level=%.4f",
                prev,
                boundary,
                self._session.level,
            )

        # Update chunk progress
        w = config.LEVEL_BAR_WIDTH
        h = config.CHUNK_PROGRESS_HEIGHT
        queued_w = int(self._chunk_manager.queued_fraction() * w)
        done_w = int(self._chunk_manager.progress_fraction() * w)
        self._chunk_canvas.coords(self._chunk_bar_queued, 0, 0, queued_w, h)
        self._chunk_canvas.coords(self._chunk_bar_done, 0, 0, done_w, h)

        after_id = self._root.after(config.LEVEL_UPDATE_MS, self._update_level)
        self._pending_after_ids.append(after_id)

    def destroy(self) -> None:
        """Clean up the window if still alive."""
        self._cancel_pending_afters()
        if self._window and self._window.winfo_exists():
            self._window.destroy()
            self._window = None
