# Generated By: Claude Code (Claude Opus 4.6)
"""PID lockfile management for single-instance enforcement."""

import logging
import os
import sys
from pathlib import Path

from local_transcribe_ui.settings import _settings_path

logger = logging.getLogger(__name__)


class LockAcquireError(Exception):
    """Raised when the lock file cannot be acquired."""


def _lock_path() -> Path:
    """Return path to the PID lockfile."""
    from local_transcribe_ui import config

    return _settings_path().parent / config.LOCK_FILENAME


def _is_pid_alive(pid: int) -> bool:
    """Check if a process with the given PID is running."""
    if sys.platform == "win32":
        import ctypes

        PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
        handle = ctypes.windll.kernel32.OpenProcess(
            PROCESS_QUERY_LIMITED_INFORMATION, False, pid
        )
        if handle:
            ctypes.windll.kernel32.CloseHandle(handle)
            return True
        return False
    try:
        os.kill(pid, 0)
        return True
    except PermissionError:
        return True
    except OSError:
        return False


def _read_lock_pid(path: Path) -> int | None:
    """Read and return the PID from the lockfile, or None if unreadable."""
    if not path.exists():
        return None
    try:
        return int(path.read_text().strip())
    except (ValueError, OSError):
        return None


def _write_lock_file(path: Path, pid: int) -> None:
    """Atomically create lockfile with PID. Raises FileExistsError if exists."""
    fd = None
    try:
        fd = os.open(str(path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        os.write(fd, str(pid).encode())
    finally:
        if fd is not None:
            os.close(fd)


def acquire_lock(*, path: Path | None = None) -> None:
    """Acquire the PID lockfile. Raises LockAcquireError if held by another.

    Uses O_CREAT|O_EXCL for atomic file creation to prevent race conditions.
    """
    lock = path or _lock_path()
    my_pid = os.getpid()
    lock.parent.mkdir(parents=True, exist_ok=True)

    try:
        _write_lock_file(lock, my_pid)
        logger.debug("lock acquired: pid=%d", my_pid)
        return
    except FileExistsError:
        pass

    lock_pid = _read_lock_pid(lock)

    if lock_pid is not None and lock_pid == my_pid:
        logger.debug("lock already owned by us: pid=%d", my_pid)
        return

    if lock_pid is not None and _is_pid_alive(lock_pid):
        logger.debug("lock held by live process: pid=%d", lock_pid)
        raise LockAcquireError(
            "Another voice recording session is already running. "
            "Finish that session before starting a new one."
        )

    logger.debug("removing stale lock: pid=%s", lock_pid)
    try:
        lock.unlink()
    except OSError:
        pass
    try:
        _write_lock_file(lock, my_pid)
        logger.debug("lock acquired after stale cleanup: pid=%d", my_pid)
    except FileExistsError:
        raise LockAcquireError(
            "Failed to acquire lock. Another session may have started."
        )


def release_lock(*, path: Path | None = None) -> None:
    """Remove the PID lockfile only if we own it."""
    lock = path or _lock_path()
    lock_pid = _read_lock_pid(lock)
    if lock_pid is not None and lock_pid != os.getpid():
        logger.warning(
            "lock not owned by us (owner=%d, self=%d), not releasing",
            lock_pid,
            os.getpid(),
        )
        return
    try:
        lock.unlink()
        logger.debug("lock released")
    except OSError:
        pass
