# Generated By: Claude Code (Claude Opus 4.6)
"""SKILL.md output protocol — [BEGIN]/[END]/[CANCEL] markers."""

from local_transcribe_ui import __version__


def emit_begin(*, flush: bool = False) -> None:
    """Print the [BEGIN version=...] marker to stdout."""
    print(f"[BEGIN version={__version__}]", flush=flush)


def emit_end() -> None:
    """Print the [END] marker to stdout."""
    print("[END]")


def emit_cancel() -> None:
    """Write the [CANCEL] marker to stdout.

    Uses os.write to bypass any buffering or redirection that tkinter
    may apply to sys.stdout during event handler processing.
    """
    import os

    os.write(1, b"[CANCEL]\n")
