# Generated By: Claude Code (Claude Opus 4.6)
"""Embeddable recording controller — reusable core without CLI concerns.

Coordinates recording, transcription, and GUI without owning the mainloop,
lockfile, or stdout protocol. Accepts an existing tk.Tk root and delivers
results via callbacks.
"""

from __future__ import annotations

import logging
import os
import tkinter as tk
from typing import Callable

from local_transcribe import (
    ChunkManager,
    RecordingSession,
    SilenceDetector,
    save_wav_to,
    start_whisper_preload,
)
from local_transcribe.recording import RecordingError
from local_transcribe_ui.gui import RecordingWindow
from local_transcribe_ui.settings import Settings, load_settings

logger = logging.getLogger(__name__)


class RecordingController:
    """Embeddable recording controller for use in any Tk application.

    Unlike AppController, this class:
    - Accepts an existing tk.Tk root (does not create one)
    - Delivers results via callbacks (does not print to stdout)
    - Does not call sys.exit()
    - Does not call mainloop()
    - Does not manage a lockfile

    Args:
        root: Existing tk.Tk root window.
        model_size: Whisper model size.
        device_id: Audio input device ID (None for default).
        on_done: Called with transcript text when recording completes.
        on_cancel: Called when user cancels recording.
        on_error: Called with error message on failure.
        on_stream_chunk: Called with each transcript chunk as it completes.
        wav_output: Optional path to save recorded audio.
        compute_device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
    """

    def __init__(
        self,
        root: tk.Tk,
        *,
        model_size: str | None = None,
        device_id: int | None = None,
        on_done: Callable[[str], None] | None = None,
        on_cancel: Callable[[], None] | None = None,
        on_error: Callable[[str], None] | None = None,
        on_stream_chunk: Callable[[str], None] | None = None,
        wav_output: str | None = None,
        compute_device: str | None = None,
        compute_type: str | None = None,
        silence_threshold: float | None = None,
        silence_duration: float | None = None,
        min_chunk_seconds: float | None = None,
    ):
        self._root = root
        self._model_size = model_size
        self._device_id = device_id
        self._on_done = on_done
        self._on_cancel = on_cancel
        self._on_error = on_error
        self._on_stream_chunk = on_stream_chunk
        self._wav_output = wav_output
        self._compute_device = compute_device
        self._compute_type = compute_type
        self._silence_threshold = silence_threshold
        self._silence_duration = silence_duration
        self._min_chunk_seconds = min_chunk_seconds

        self._settings: Settings = load_settings()
        self._session: RecordingSession | None = None
        self._chunk_manager: ChunkManager | None = None
        self._recording_window: RecordingWindow | None = None

    def start(self) -> None:
        """Create components, start recording, show popup window.

        Non-blocking — the caller owns the mainloop.
        """
        preload_kwargs: dict = {}
        if self._model_size is not None:
            preload_kwargs["model_size"] = self._model_size
        if self._compute_device is not None:
            preload_kwargs["device"] = self._compute_device
        if self._compute_type is not None:
            preload_kwargs["compute_type"] = self._compute_type
        start_whisper_preload(**preload_kwargs)

        chunk_kwargs: dict = {}
        if self._model_size is not None:
            chunk_kwargs["model_size"] = self._model_size
        if self._compute_device is not None:
            chunk_kwargs["device"] = self._compute_device
        if self._compute_type is not None:
            chunk_kwargs["compute_type"] = self._compute_type
        self._chunk_manager = ChunkManager(**chunk_kwargs)

        silence_kwargs: dict = {}
        if self._silence_threshold is not None:
            silence_kwargs["threshold"] = self._silence_threshold
        if self._silence_duration is not None:
            silence_kwargs["duration_s"] = self._silence_duration
        if self._min_chunk_seconds is not None:
            silence_kwargs["min_chunk_s"] = self._min_chunk_seconds
        silence_detector = SilenceDetector(**silence_kwargs)

        if self._on_stream_chunk:
            self._chunk_manager.set_stream_callback(self._on_stream_chunk)
        self._chunk_manager.start_worker()

        try:
            self._session = RecordingSession(
                device_id=self._device_id,
                chunk_manager=self._chunk_manager,
                silence_detector=silence_detector,
            )
        except RecordingError as e:
            logger.error("%s", e)
            if self._on_error:
                self._on_error(str(e))
            return

        self._recording_window = RecordingWindow(
            self._root,
            self,
            self._settings,
            self._session,
            self._chunk_manager,
        )

        # Get device name for display
        try:
            from local_transcribe.recording import _sd

            device_name = _sd().query_devices(self._session._device_id)["name"]
        except Exception:
            device_name = "Unknown"

        self._session.start()
        self._recording_window.show(cwd=os.getcwd(), device_name=device_name)

    def on_recording_done(self) -> None:
        """Called by RecordingWindow when transcription completes."""
        assert self._session is not None
        assert self._chunk_manager is not None

        try:
            audio_data = self._session.stop()
        except RecordingError:
            audio_data = None

        if self._wav_output and audio_data is not None:
            wav_path = os.path.abspath(self._wav_output)
            save_wav_to(audio_data, wav_path)
            logger.info("Saved audio to %s", wav_path)

        transcript = self._chunk_manager.get_transcript()

        if self._recording_window:
            self._recording_window.destroy()
            self._recording_window = None

        if self._on_done:
            self._on_done(transcript)

    def on_recording_cancelled(self) -> None:
        """Called by RecordingWindow when user cancels."""
        assert self._session is not None
        self._session.abort()

        if self._recording_window:
            self._recording_window.destroy()
            self._recording_window = None

        if self._on_cancel:
            self._on_cancel()

    @property
    def is_active(self) -> bool:
        """Whether a recording session is currently active."""
        return self._session is not None and self._session.is_recording
