# Generated By: Claude Code (Claude Opus 4.6)
"""Settings persistence using dataclass and atomic JSON I/O."""

import json
import logging
import os
import platform
from dataclasses import asdict, dataclass, fields
from pathlib import Path

from local_transcribe_ui import config

logger = logging.getLogger(__name__)


@dataclass
class Settings:
    """User-configurable application settings."""

    window_x: int | None = config.DEFAULT_WINDOW_X
    window_y: int | None = config.DEFAULT_WINDOW_Y


def _settings_path() -> Path:
    """Platform-appropriate settings file path."""
    if platform.system() == "Windows":
        base = Path(os.environ.get("APPDATA", Path.home()))
    else:
        base = Path.home() / ".config"
    return base / config.APP_NAME / config.SETTINGS_FILENAME


def load_settings(*, path: Path | None = None) -> Settings:
    """Load settings from JSON. Returns defaults on any failure."""
    target = path or _settings_path()

    try:
        raw = json.loads(target.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        logger.debug("settings load failed, using defaults error=%s", exc)
        return Settings()

    if not isinstance(raw, dict):
        return Settings()

    known = {f.name for f in fields(Settings)}
    defaults = Settings()

    for field_info in fields(Settings):
        if field_info.name not in raw or field_info.name not in known:
            continue
        value = raw[field_info.name]
        default = getattr(defaults, field_info.name)

        if isinstance(default, int) and not isinstance(default, bool):
            if isinstance(value, bool):
                continue
        if default is not None and not isinstance(value, type(default)):
            logger.debug("skipping invalid field=%s value=%r", field_info.name, value)
            continue

        setattr(defaults, field_info.name, value)

    return defaults


def save_settings(settings: Settings, *, path: Path | None = None) -> None:
    """Atomically save settings to JSON."""
    target = path or _settings_path()
    target.parent.mkdir(parents=True, exist_ok=True)

    data = json.dumps(asdict(settings), indent=2, ensure_ascii=False)

    tmp = target.with_suffix(".tmp")
    try:
        tmp.write_text(data + "\n", encoding="utf-8")
        tmp.replace(target)
    except OSError as exc:
        logger.error("failed to save settings error=%s", exc)
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass
