#!/usr/bin/env python3
# Generated By: Claude Code (claude-opus-5)
"""Probe which sample rates each audio input device actually accepts.

Run on the machine that fails, not in CI:

    local-transcribe devices          # for the IDs
    python scripts/explore/probe_input_rates.py

For every input device it prints the PortAudio-reported default rate, then
whether check_input_settings and a real InputStream open succeed at each
candidate rate. `check` and `open` disagreeing matters: RecordingSession
picks its capture rate from `check`, so a device where check passes and
open fails would still raise PaErrorCode -9997.

Opening a real stream on some JACK devices (filters, level meters) blocks
indefinitely, so `--check-only` skips the open test. Output is flushed per
line to keep partial results when a device does hang.
"""

import argparse
import sounddevice as sd

from local_transcribe.transcription import AUDIO_CHANNELS, SAMPLE_RATE

RATES = [SAMPLE_RATE, 22050, 32000, 44100, 48000]
DTYPE = "int16"


def _probe(device_id: int, rate: int, check_only: bool) -> str:
    try:
        sd.check_input_settings(
            device=device_id, channels=AUDIO_CHANNELS, dtype=DTYPE, samplerate=rate
        )
        check = "check=ok"
    except Exception as e:
        return f"check=FAIL ({type(e).__name__}: {e})"

    if check_only:
        return check

    try:
        with sd.InputStream(
            samplerate=rate, channels=AUDIO_CHANNELS, dtype=DTYPE, device=device_id
        ):
            pass
        return f"{check} open=ok"
    except Exception as e:
        return f"{check} open=FAIL ({type(e).__name__}: {e})"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="skip the real stream open (some JACK devices block on it)",
    )
    parser.add_argument(
        "--device", type=int, default=None, help="probe only this device ID"
    )
    args = parser.parse_args()

    print(f"PortAudio: {sd.get_portaudio_version()[1]}", flush=True)
    default_input = sd.default.device[0]

    for device_id, dev in enumerate(sd.query_devices()):
        if dev["max_input_channels"] < AUDIO_CHANNELS:
            continue
        if args.device is not None and device_id != args.device:
            continue
        host = sd.query_hostapis(dev["hostapi"])["name"]
        mark = " <- sd.default.device[0]" if device_id == default_input else ""
        print(
            f"\n[{device_id}] {dev['name']} ({host})"
            f" default_samplerate={dev['default_samplerate']:.0f}{mark}",
            flush=True,
        )
        for rate in RATES:
            result = _probe(device_id, rate, args.check_only)
            print(f"    {rate:>6} Hz  {result}", flush=True)


if __name__ == "__main__":
    main()
