# Generated By: Claude Code (Claude Opus 4.6)
"""local-transcribe: Chunked local speech-to-text engine using faster-whisper."""

__version__ = "0.1.0"

from local_transcribe.chunking import ChunkManager, SilenceDetector, trim_silence
from local_transcribe.recording import (
    RecordingError,
    RecordingSession,
    get_default_input_device,
    get_input_devices,
)
from local_transcribe.transcription import (
    SAMPLE_RATE,
    compute_audio_level,
    get_or_create_model,
    save_wav_to,
    start_whisper_preload,
    transcribe_audio,
    transcribe_wav,
)

__all__ = [
    # chunking
    "ChunkManager",
    "SilenceDetector",
    "trim_silence",
    # recording
    "RecordingError",
    "RecordingSession",
    "get_default_input_device",
    "get_input_devices",
    # transcription
    "SAMPLE_RATE",
    "compute_audio_level",
    "get_or_create_model",
    "save_wav_to",
    "start_whisper_preload",
    "transcribe_audio",
    "transcribe_wav",
]
