# Generated By: Claude Code (Claude Opus 4.6)
"""Chunked transcription support — SilenceDetector and ChunkManager.

SilenceDetector tracks audio levels to find natural chunk boundaries.
ChunkManager coordinates background transcription of audio chunks.
"""

import logging
import math
import queue
import threading
from typing import Callable

import numpy as np

from local_transcribe.transcription import (
    SAMPLE_RATE,
    _DEFAULT_BEAM_SIZE,
    _DEFAULT_COMPUTE_TYPE,
    _DEFAULT_DEVICE,
    _DEFAULT_MODEL_SIZE,
    _segments_to_text,
    compute_audio_level,
    transcribe_audio_segments,
)

logger = logging.getLogger(__name__)

_DEFAULT_SILENCE_THRESHOLD = 0.08
_DEFAULT_SILENCE_BUFFER_S = 0.5


class SilenceDetector:
    """Detects silence gaps in an audio stream for chunk boundary selection.

    Tracks consecutive silent callbacks and fires once when silence exceeds
    a duration threshold. The returned chunk index marks where to cut,
    adjusted by a buffer to avoid clipping speech.

    Args:
        threshold: Audio level (0.0-1.0) below which is considered silence.
        duration_s: Seconds of continuous silence required to trigger.
        min_chunk_s: Minimum accumulated audio before triggering.
        buffer_s: Silence padding kept at the end of a chunk cut.
        callback_interval_s: Approximate time between audio callbacks.
    """

    def __init__(
        self,
        *,
        threshold: float = _DEFAULT_SILENCE_THRESHOLD,
        duration_s: float = 1.0,
        min_chunk_s: float = 10.0,
        buffer_s: float = _DEFAULT_SILENCE_BUFFER_S,
        callback_interval_s: float = 0.01,
    ):
        self._threshold = threshold
        self._duration_s = duration_s
        self._min_chunk_s = min_chunk_s
        self._buffer_callbacks = max(0, math.floor(buffer_s / callback_interval_s))
        self._min_silent_callbacks = math.ceil(duration_s / callback_interval_s)
        self._consecutive_silent = 0
        self._silence_onset_idx: int | None = None
        self._triggered = False

    def feed(self, level: float, chunk_index: int, accumulated_s: float) -> int | None:
        """Feed an audio level sample.

        Args:
            level: Current audio level (0.0-1.0).
            chunk_index: Index into the chunks list for this callback.
            accumulated_s: Total audio accumulated since last flush.

        Returns:
            Chunk index to use as the cut boundary, or None if no trigger.
            The boundary includes buffer_s of silence padding and is an
            unclamped hint — callers (e.g. ChunkManager.flush) should
            clamp to the actual chunks list length.
        """
        if level < self._threshold:
            if self._consecutive_silent == 0:
                self._silence_onset_idx = chunk_index
            self._consecutive_silent += 1

            if (
                not self._triggered
                and self._consecutive_silent >= self._min_silent_callbacks
                and accumulated_s >= self._min_chunk_s
                and self._silence_onset_idx is not None
            ):
                self._triggered = True
                boundary = self._silence_onset_idx + self._buffer_callbacks
                return boundary
        else:
            self._consecutive_silent = 0
            self._silence_onset_idx = None
            self._triggered = False

        return None

    def reset(self) -> None:
        """Clear all state. Call when resuming from pause."""
        self._consecutive_silent = 0
        self._silence_onset_idx = None
        self._triggered = False


def trim_silence(
    audio: np.ndarray,
    *,
    sample_rate: int = SAMPLE_RATE,
    threshold: float = _DEFAULT_SILENCE_THRESHOLD,
    buffer_s: float = _DEFAULT_SILENCE_BUFFER_S,
) -> np.ndarray | None:
    """Trim silence from both ends of an audio chunk.

    Scans for the first and last samples where the level exceeds the
    threshold, then keeps buffer_s of padding on each side.

    Returns None if no speech is found (entire chunk is silence).
    """
    block_size = max(1, sample_rate // 40)  # ~25ms blocks, matches callback size
    buffer_samples = int(buffer_s * sample_rate)
    n = len(audio)

    # Find first block with speech
    first_speech = None
    for i in range(0, n, block_size):
        block = audio[i : i + block_size]
        peak = int(np.max(np.abs(block)))
        level = compute_audio_level(peak)
        if level >= threshold:
            first_speech = i
            break

    if first_speech is None:
        return None  # all silence

    # Find last block with speech
    last_speech = first_speech
    for i in range(0, n, block_size):
        block = audio[i : i + block_size]
        peak = int(np.max(np.abs(block)))
        level = compute_audio_level(peak)
        if level >= threshold:
            last_speech = i + block_size

    start = max(0, first_speech - buffer_samples)
    end = min(n, last_speech + buffer_samples)

    return audio[start:end]


class ChunkManager:
    """Coordinates background transcription of audio chunks.

    Tracks which audio has been sent for transcription vs. still accumulating.
    A single worker thread processes chunks sequentially from a queue,
    reusing the Whisper model across calls.

    Args:
        model_size: Whisper model size (tiny, base, small, medium, large).
        device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
        beam_size: Beam search width. Lower = faster, higher = more accurate.
        sample_rate: Audio sample rate (for progress calculation).
    """

    def __init__(
        self,
        *,
        model_size: str = _DEFAULT_MODEL_SIZE,
        device: str = _DEFAULT_DEVICE,
        compute_type: str = _DEFAULT_COMPUTE_TYPE,
        beam_size: int = _DEFAULT_BEAM_SIZE,
        sample_rate: int = SAMPLE_RATE,
        vad_filter: bool = True,
        condition_on_previous_text: bool = True,
    ):
        self._model_size = model_size
        self._device = device
        self._compute_type = compute_type
        self._beam_size = beam_size
        self._sample_rate = sample_rate
        self._vad_filter = vad_filter
        self._condition_on_previous_text = condition_on_previous_text
        self._chunks_ref: list[np.ndarray] | None = None
        self._boundary: int = 0
        self._queue: queue.Queue[tuple[np.ndarray, int] | None] = queue.Queue()
        self._transcripts: list[str] = []
        self._all_segments: list[dict] = []
        self._errors: list[Exception] = []
        self._fatal_error: RuntimeError | None = None
        self._stream_callback: Callable[[str], None] | None = None
        self._total_samples_sent: int = 0
        self._total_samples_done: int = 0
        self._worker: threading.Thread | None = None
        self._finished = threading.Event()

    def bind_chunks(self, chunks: list[np.ndarray]) -> None:
        """Bind to the recording's chunks list."""
        self._chunks_ref = chunks

    @property
    def boundary(self) -> int:
        """Index into chunks list: everything before this has been flushed."""
        return self._boundary

    def set_stream_callback(self, callback: Callable[[str], None]) -> None:
        """Set callback for streaming transcripts as they complete."""
        self._stream_callback = callback

    def start_worker(self) -> None:
        """Start the background transcription thread."""
        self._worker = threading.Thread(target=self._worker_loop, daemon=True)
        self._worker.start()

    def flush(self, boundary: int | None = None) -> bool:
        """Enqueue audio from current boundary to the given index.

        Args:
            boundary: Chunk index to flush up to. If None, flush all.

        Returns:
            True if audio was enqueued, False if nothing new.
        """
        if self._chunks_ref is None:
            return False

        end = len(self._chunks_ref) if boundary is None else boundary
        end = min(end, len(self._chunks_ref))

        if end <= self._boundary:
            return False

        audio = np.concatenate(self._chunks_ref[self._boundary : end], axis=0)
        self._boundary = end
        sample_offset = self._total_samples_sent
        self._total_samples_sent += len(audio)
        self._queue.put((audio, sample_offset))
        return True

    def finish(self, timeout: float = 30.0) -> None:
        """Flush remaining audio, signal worker to stop, and optionally wait.

        The worker sets _finished when it exits. Use timeout=0 to send the
        sentinel without blocking (for async polling via is_done()).
        """
        self.flush()
        if self._worker is not None:
            self._queue.put(None)  # sentinel
            if timeout > 0:
                self._worker.join(timeout=timeout)
        else:
            self._finished.set()

    def get_transcript(self) -> str:
        """Join all completed transcripts."""
        return " ".join(t for t in self._transcripts if t).strip()

    def get_segments(self) -> list[dict]:
        """Return all completed segments with recording-relative timestamps."""
        return list(self._all_segments)

    def total_samples_recorded(self) -> int:
        """Total samples in the bound chunks list (including un-flushed)."""
        if self._chunks_ref is None:
            return 0
        return sum(len(c) for c in self._chunks_ref)

    def queued_fraction(self) -> float:
        """Fraction of recorded audio that has been queued (0.0-1.0)."""
        total = self.total_samples_recorded()
        if total == 0:
            return 0.0
        return self._total_samples_sent / total

    def progress_fraction(self) -> float:
        """Fraction of all recorded audio that has been transcribed (0.0-1.0).

        Denominator is total recorded samples (not just flushed), so the bar
        reflects how much of the full recording is done. New audio being
        recorded pushes the fraction down.
        """
        total = self.total_samples_recorded()
        if total == 0:
            return 0.0
        return self._total_samples_done / total

    def is_done(self) -> bool:
        """True when worker has finished processing all chunks."""
        return self._finished.is_set()

    @property
    def fatal_error(self) -> RuntimeError | None:
        """Non-recoverable error that stopped the worker, if any."""
        return self._fatal_error

    def _worker_loop(self) -> None:
        """Process chunks from the queue until sentinel."""
        chunk_num = 0
        try:
            while True:
                item = self._queue.get()
                if item is None:
                    break
                audio, sample_offset = item
                chunk_num += 1
                original_samples = len(audio)

                # Trim silence from both ends
                trimmed = trim_silence(audio, sample_rate=self._sample_rate)
                if trimmed is None:
                    logger.info(
                        "chunk %d: skipped, all silence (%d samples)",
                        chunk_num,
                        original_samples,
                    )
                    self._total_samples_done += original_samples
                    continue

                duration_s = len(trimmed) / self._sample_rate
                logger.info(
                    "chunk %d: samples=%d, trimmed=%d, duration=%.1fs",
                    chunk_num,
                    original_samples,
                    len(trimmed),
                    duration_s,
                )
                try:
                    # Capture loop-local values for the closure. Both are
                    # int copies, so the closure is safe even though it is
                    # defined inside the loop.
                    chunk_samples = len(audio)
                    samples_before = self._total_samples_done

                    def on_segment_progress(fraction: float) -> None:
                        self._total_samples_done = samples_before + int(
                            fraction * chunk_samples
                        )

                    segments = transcribe_audio_segments(
                        trimmed,
                        model_size=self._model_size,
                        device=self._device,
                        compute_type=self._compute_type,
                        beam_size=self._beam_size,
                        vad_filter=self._vad_filter,
                        condition_on_previous_text=(self._condition_on_previous_text),
                        progress_callback=on_segment_progress,
                    )
                    # Ensure we account for the full chunk
                    self._total_samples_done = samples_before + chunk_samples

                    # Offset segment timestamps to recording-relative
                    time_offset = sample_offset / self._sample_rate
                    for seg in segments:
                        seg["start"] += time_offset
                        seg["end"] += time_offset
                    self._all_segments.extend(segments)

                    text = _segments_to_text(segments)
                    if text:
                        self._transcripts.append(text)
                        if self._stream_callback:
                            self._stream_callback(text)
                        logger.debug(
                            "chunk %d transcribed: %d chars",
                            chunk_num,
                            len(text),
                        )
                    else:
                        logger.debug("chunk %d: no speech detected", chunk_num)
                except RuntimeError:
                    # Non-recoverable (missing DLLs, CUDA failures) — stop
                    raise
                except Exception as e:
                    logger.error("Chunk transcription failed: %s", e)
                    self._errors.append(e)
                    self._total_samples_done += len(audio)
        except RuntimeError as e:
            logger.error("Fatal transcription error: %s", e)
            self._fatal_error = e
        finally:
            self._finished.set()
