# Generated By: Claude Code (Claude Opus 4.6)
"""Audio recording via sounddevice.

Provides RecordingSession for capturing audio from a microphone with
level metering and silence-triggered chunk flushing. No GUI dependency.
"""

from __future__ import annotations

import logging
import time
from typing import Any

import numpy as np

from local_transcribe.chunking import ChunkManager, SilenceDetector
from local_transcribe.transcription import (
    AUDIO_CHANNELS,
    SAMPLE_RATE,
    compute_audio_level,
)

logger = logging.getLogger(__name__)

AUDIO_DTYPE = "int16"


def _sd():
    """Lazy import of sounddevice (requires PortAudio)."""
    import sounddevice as sd

    return sd


def _av():
    """Lazy import of PyAV (used only when the device rejects SAMPLE_RATE)."""
    import av

    return av


_EMPTY_BLOCK = np.empty((0, AUDIO_CHANNELS), dtype=AUDIO_DTYPE)


class RecordingError(Exception):
    """Raised when audio recording fails."""


def get_default_input_device() -> int:
    """Return the sounddevice index of the system default input device."""
    default = _sd().default.device[0]
    if not isinstance(default, int) or default < 0:
        devices = _sd().query_devices()
        for i, dev in enumerate(devices):
            if dev["max_input_channels"] > 0:
                return i
        raise RecordingError("No input devices found.")
    return int(default)


def get_input_devices() -> list[dict]:
    """Return a list of available input devices with id and name."""
    devices = _sd().query_devices()
    result = []
    for i, dev in enumerate(devices):
        if dev["max_input_channels"] > 0:
            result.append({"id": i, "name": dev["name"]})
    return result


class RecordingSession:
    """Manages audio capture from a microphone.

    Captures audio into chunks, computes level for metering, and optionally
    integrates with SilenceDetector and ChunkManager for background
    transcription during recording.

    Memory note: audio chunks accumulate in memory (~3.2MB/minute at 16kHz
    int16). For very long recordings, consider periodic flush via ChunkManager.

    Args:
        device_id: Sounddevice input device index. None for default.
        chunk_manager: Optional ChunkManager for background transcription.
        silence_detector: Optional SilenceDetector for automatic chunk flushing.
    """

    def __init__(
        self,
        *,
        device_id: int | None = None,
        chunk_manager: ChunkManager | None = None,
        silence_detector: SilenceDetector | None = None,
    ):
        self._device_id = (
            device_id if device_id is not None else get_default_input_device()
        )
        self._chunk_manager = chunk_manager
        self._silence_detector = silence_detector

        self._chunks: list[np.ndarray] = []
        self._recording = False
        self._paused = False
        self._start_time = 0.0
        self._paused_elapsed = 0.0
        self._pause_start = 0.0

        self._callback_count = 0
        self._current_level = 0.0
        self._silence_flush_boundary: int | None = None

        self._stream: Any = None
        self._capture_rate = SAMPLE_RATE
        self._resampler: Any = None

        if chunk_manager is not None:
            chunk_manager.bind_chunks(self._chunks)

    @property
    def chunks(self) -> list[np.ndarray]:
        """The list of recorded audio chunks."""
        return self._chunks

    @property
    def level(self) -> float:
        """Current audio level (0.0-1.0)."""
        return self._current_level

    @property
    def is_recording(self) -> bool:
        """True if the session is actively recording (not paused)."""
        return self._recording and not self._paused

    @property
    def is_paused(self) -> bool:
        """True if recording is paused."""
        return self._paused

    def consume_silence_flush_boundary(self) -> int | None:
        """Return and clear the silence-triggered flush boundary.

        The boundary is set by the audio callback when SilenceDetector
        fires. Returns the chunk index once, then None until the next
        trigger. Callers should use this to drive ChunkManager.flush().
        """
        boundary = self._silence_flush_boundary
        self._silence_flush_boundary = None
        return boundary

    def elapsed_seconds(self) -> float:
        """Seconds elapsed while actively recording (excludes paused time)."""
        if not self._recording:
            return 0.0
        now = time.time()
        total = now - self._start_time - self._paused_elapsed
        if self._paused:
            total -= now - self._pause_start
        return max(0.0, total)

    def _pick_capture_rate(self) -> int:
        """Return SAMPLE_RATE if the device accepts it, else its default rate.

        Many microphones only expose their native rate (typically 44100 or
        48000) and reject 16000 outright, which surfaces as PortAudio
        "Invalid sample rate [PaErrorCode -9997]".
        """
        sd = _sd()
        try:
            sd.check_input_settings(
                device=self._device_id,
                channels=AUDIO_CHANNELS,
                dtype=AUDIO_DTYPE,
                samplerate=SAMPLE_RATE,
            )
            return SAMPLE_RATE
        except Exception:
            rate = int(sd.query_devices(self._device_id)["default_samplerate"])
            logger.info(
                "device %d rejected %d Hz; capturing at %d Hz and resampling",
                self._device_id,
                SAMPLE_RATE,
                rate,
            )
            return rate

    def start(self) -> None:
        """Open the audio stream and begin recording.

        Raises:
            RecordingError: If the microphone cannot be accessed.
        """
        self._capture_rate = self._pick_capture_rate()
        if self._capture_rate != SAMPLE_RATE:
            self._resampler = _av().audio.resampler.AudioResampler(
                format="s16", layout="mono", rate=SAMPLE_RATE
            )

        try:
            self._stream = _sd().InputStream(
                samplerate=self._capture_rate,
                channels=AUDIO_CHANNELS,
                dtype=AUDIO_DTYPE,
                callback=self._audio_callback,
                device=self._device_id,
            )
        except Exception as e:
            raise RecordingError(f"Failed to access microphone: {e}") from e

        self._recording = True
        self._start_time = time.time()
        self._stream.start()

    def pause(self) -> None:
        """Pause recording. Flushes accumulated audio if chunk_manager is set."""
        if not self._recording or self._paused:
            return
        if self._chunk_manager is not None:
            prev = self._chunk_manager.boundary
            flushed = self._chunk_manager.flush()
            if flushed:
                logger.debug(
                    "pause flush: chunks %d-%d", prev, self._chunk_manager.boundary
                )
            self._silence_flush_boundary = None
        self._pause_start = time.time()
        self._paused = True
        if self._silence_detector is not None:
            self._silence_detector.reset()

    def resume(self) -> None:
        """Resume recording after a pause."""
        if not self._paused:
            return
        self._paused_elapsed += time.time() - self._pause_start
        self._paused = False
        if self._silence_detector is not None:
            self._silence_detector.reset()

    def stop(self) -> np.ndarray:
        """Stop recording and return the concatenated audio data.

        Raises:
            RecordingError: If no audio was captured.
        """
        self._recording = False
        if self._stream is not None:
            self._stream.stop()
            self._stream.close()
            self._stream = None

        if self._resampler is not None:
            tail = self._resample(None)
            if len(tail):
                self._chunks.append(tail)

        if not self._chunks:
            raise RecordingError("No audio captured.")

        audio_data = np.concatenate(self._chunks, axis=0)
        duration = len(audio_data) / SAMPLE_RATE
        logger.info("Captured %.1fs of audio.", duration)
        return audio_data

    def abort(self) -> None:
        """Stop recording without returning audio."""
        self._recording = False
        if self._stream is not None:
            self._stream.stop()
            self._stream.close()
            self._stream = None

    def _audio_callback(self, indata, _frames, _time_info, status):
        """Sounddevice callback — runs in audio thread."""
        self._callback_count += 1
        if status:
            logger.warning("audio_callback status: %s", status)
        if self._recording and not self._paused:
            block = indata.copy() if self._resampler is None else self._resample(indata)
            peak = int(np.max(np.abs(indata)))
            if not len(block):
                self._current_level = compute_audio_level(peak)
                return
            self._chunks.append(block)
            self._current_level = compute_audio_level(peak)
            if self._callback_count % 50 == 0:
                logger.debug(
                    "callback=%d, chunks=%d, peak=%d, level=%.4f",
                    self._callback_count,
                    len(self._chunks),
                    peak,
                    self._current_level,
                )
            # Feed silence detector
            if self._silence_detector is not None and self._chunk_manager is not None:
                accumulated_s = (
                    (len(self._chunks) - self._chunk_manager.boundary)
                    * len(block)
                    / SAMPLE_RATE
                )
                boundary = self._silence_detector.feed(
                    self._current_level, len(self._chunks) - 1, accumulated_s
                )
                if boundary is not None:
                    self._silence_flush_boundary = boundary
        else:
            self._current_level = 0.0

    def _resample(self, indata) -> np.ndarray:
        """Resample one capture-rate block to SAMPLE_RATE.

        Pass None to flush the resampler's buffered tail. Returns an
        (N, AUDIO_CHANNELS) int16 array, possibly empty — libswresample
        buffers, so a single input block need not yield output.
        """
        frame = None
        if indata is not None:
            frame = _av().AudioFrame.from_ndarray(
                np.ascontiguousarray(indata.T), format="s16", layout="mono"
            )
            frame.sample_rate = self._capture_rate
        out = [f.to_ndarray().T for f in self._resampler.resample(frame)]
        return np.concatenate(out, axis=0) if out else _EMPTY_BLOCK
