# Generated By: Claude Code (Claude Opus 4.6)
"""Whisper model management and transcription.

Handles model caching, background preloading, and transcription of WAV files
and raw audio data.
"""

import contextlib
import logging
import os
import sys
import threading
import time
import wave
from typing import Callable

import numpy as np

logger = logging.getLogger(__name__)

# Fixed by Whisper's requirements — not configurable.
SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH = 2

# Defaults for configurable parameters. Private — consumers pass explicit
# values or accept these defaults through function signatures.
_DEFAULT_MODEL_SIZE = "small"
_DEFAULT_BEAM_SIZE = 5
_DEFAULT_DEVICE = "cpu"
_DEFAULT_COMPUTE_TYPE = "int8"
_DEFAULT_GAIN = 4.0

# Background import of faster-whisper (heavy C++ bindings).
# Started early so the import finishes during recording.
_whisper_preload_lock = threading.Lock()
_whisper_preload_started = False
_whisper_module_ready = threading.Event()
_WhisperModel = None

# Model instance cache — avoids reloading for each chunk.
# Cache key is (model_size, device, compute_type).
_model_lock = threading.Lock()
_cached_model = None
_cached_model_key: tuple[str, str, str] | None = None


@contextlib.contextmanager
def _suppress_stdout():
    """Temporarily redirect stdout to devnull.

    Used to suppress ctranslate2/faster-whisper progress output.
    Thread-safe: each caller captures and restores its own saved reference.
    """
    with open(os.devnull, "w") as devnull:
        saved, sys.stdout = sys.stdout, devnull
        try:
            yield
        finally:
            sys.stdout = saved


def compute_audio_level(peak: int, *, gain: float = _DEFAULT_GAIN) -> float:
    """Normalize an int16 peak sample to a 0.0-1.0 level with gain boost.

    Args:
        peak: Absolute peak sample value (0-32768).
        gain: Amplification factor applied before clamping. Higher values
            make quiet signals register as louder. Default 4.0.
    """
    return min(peak / 32768.0 * gain, 1.0)


# DLLs that ctranslate2 needs for CUDA inference. Loading only these
# avoids the ~5s cost of eagerly loading all 14 nvidia DLLs.
_CUDA_DLLS = ("cublas64_12.dll", "cublasLt64_12.dll", "cudnn64_9.dll")


def _register_nvidia_dll_paths() -> None:
    """Load nvidia CUDA DLLs on Windows.

    The nvidia-cublas-cu12/nvidia-cudnn-cu12 pip packages install DLLs
    into site-packages/nvidia/*/bin/. ctranslate2 can't find them at
    inference time without eager loading via ctypes.CDLL.
    """
    if sys.platform != "win32":
        return
    try:
        import ctypes
        import importlib.util

        spec = importlib.util.find_spec("nvidia")
        if spec is None or spec.submodule_search_locations is None:
            return

        # Build a map of DLL filename -> full path for targeted loading
        dll_paths: dict[str, str] = {}
        for nvidia_dir in spec.submodule_search_locations:
            for entry in os.scandir(nvidia_dir):
                if entry.is_dir():
                    bin_dir = os.path.join(entry.path, "bin")
                    if os.path.isdir(bin_dir):
                        os.add_dll_directory(bin_dir)
                        for dll_entry in os.scandir(bin_dir):
                            if dll_entry.name.endswith(".dll"):
                                dll_paths[dll_entry.name] = dll_entry.path

        for name in _CUDA_DLLS:
            path = dll_paths.get(name)
            if path:
                try:
                    ctypes.CDLL(path)
                    logger.debug("loaded DLL: %s", path)
                except OSError:
                    pass
    except Exception:
        pass


def _preload_whisper(
    model_size: str | None = None,
    device: str | None = None,
    compute_type: str | None = None,
) -> None:
    """Import faster-whisper and optionally warm the model cache."""
    global _WhisperModel
    try:
        from faster_whisper import WhisperModel

        _WhisperModel = WhisperModel
    except Exception:
        pass  # transcribe functions will re-attempt and surface the error
    finally:
        _whisper_module_ready.set()

    # Eagerly load the model so it's cached before the first chunk arrives
    if model_size is not None and _WhisperModel is not None:
        try:
            get_or_create_model(
                model_size=model_size,
                device=device or _DEFAULT_DEVICE,
                compute_type=compute_type or _DEFAULT_COMPUTE_TYPE,
            )
        except Exception as e:
            logger.warning("model preload failed: %s", e)


def start_whisper_preload(
    *,
    model_size: str | None = None,
    device: str | None = None,
    compute_type: str | None = None,
) -> None:
    """Kick off background import and optional model preload.

    Args:
        model_size: If provided, eagerly load this model in the background.
        device: Inference device for preloading.
        compute_type: Model precision for preloading.
    """
    global _whisper_preload_started
    with _whisper_preload_lock:
        if _whisper_preload_started:
            return
        _whisper_preload_started = True
    # Register nvidia DLL paths on the main thread before the background
    # import triggers ctranslate2's DLL search.
    _register_nvidia_dll_paths()
    threading.Thread(
        target=_preload_whisper,
        args=(model_size, device, compute_type),
        daemon=True,
    ).start()


def _get_model_class():
    """Return the WhisperModel class, waiting for preload if needed."""
    if _whisper_preload_started:
        _whisper_module_ready.wait()
        if _WhisperModel is not None:
            return _WhisperModel
    # Preload not started or failed — import synchronously
    from faster_whisper import WhisperModel

    return WhisperModel


def get_or_create_model(
    *,
    model_size: str = _DEFAULT_MODEL_SIZE,
    device: str = _DEFAULT_DEVICE,
    compute_type: str = _DEFAULT_COMPUTE_TYPE,
):
    """Return a cached WhisperModel instance, creating one if needed.

    The model is cached at module level and reused across calls with the
    same (model_size, device, compute_type) key. This avoids the expensive
    model load for each chunk in chunked transcription.

    Args:
        model_size: Whisper model size (tiny, base, small, medium, large).
        device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
    """
    global _cached_model, _cached_model_key

    key = (model_size, device, compute_type)

    with _model_lock:
        if _cached_model is not None and _cached_model_key == key:
            logger.debug("model cache hit: %s/%s/%s", *key)
            return _cached_model

        logger.debug(
            "loading model: size=%s, device=%s, compute_type=%s",
            model_size,
            device,
            compute_type,
        )
        model_cls = _get_model_class()

        t0 = time.monotonic()
        with _suppress_stdout():
            model = model_cls(model_size, device=device, compute_type=compute_type)
        elapsed = time.monotonic() - t0
        logger.debug("model loaded in %.2fs", elapsed)

        _cached_model = model
        _cached_model_key = key
        return model


def save_wav_to(audio_data: np.ndarray, path: str) -> None:
    """Save audio data to a WAV file at the given path."""
    with wave.open(path, "wb") as wf:
        wf.setnchannels(AUDIO_CHANNELS)
        wf.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(audio_data.tobytes())


def _run_transcription(
    model,
    source,
    *,
    audio_duration: float,
    beam_size: int = _DEFAULT_BEAM_SIZE,
    vad_filter: bool = False,
    condition_on_previous_text: bool = True,
    progress_callback: Callable[[float], None] | None = None,
) -> list[dict]:
    """Run transcription with stdout suppression and progress tracking.

    Always returns structured segment data. Callers decide how to
    present it (join text, return dicts, etc.).

    Args:
        model: WhisperModel instance.
        source: WAV file path or float32 numpy array.
        audio_duration: Duration in seconds (for progress fraction).
        beam_size: Beam search width. Lower = faster, higher = more accurate.
        vad_filter: Enable Silero VAD to filter non-speech audio before
            transcription. Reduces hallucinations on silence.
        condition_on_previous_text: Use previous segment output as prompt for
            the next. Disabling prevents hallucination cascades.
        progress_callback: Called with progress fraction (0.0-1.0).

    Returns:
        List of {"start": float, "end": float, "text": str} dicts.
        Empty segments (whitespace-only after sanitization) are filtered out.
    """
    logger.debug(
        "transcribing: duration=%.1fs, beam_size=%d, vad_filter=%s, "
        "condition_on_previous_text=%s",
        audio_duration,
        beam_size,
        vad_filter,
        condition_on_previous_text,
    )
    t0 = time.monotonic()
    with _suppress_stdout():
        segments, _ = model.transcribe(
            source,
            beam_size=beam_size,
            vad_filter=vad_filter,
            condition_on_previous_text=condition_on_previous_text,
        )
        result: list[dict] = []
        for seg in segments:
            text = _sanitize_transcript(seg.text.strip())
            if text:
                result.append({"start": seg.start, "end": seg.end, "text": text})
            if progress_callback and audio_duration > 0:
                fraction = min(seg.end / audio_duration, 1.0)
                progress_callback(fraction)
    elapsed = time.monotonic() - t0
    if progress_callback:
        progress_callback(1.0)
    logger.debug(
        "transcription complete: %.2fs elapsed, %.1fx realtime, %d segments",
        elapsed,
        audio_duration / elapsed if elapsed > 0 else 0,
        len(result),
    )
    return result


def _segments_to_text(segments: list[dict]) -> str:
    """Join segment dicts into a single text string."""
    return " ".join(seg["text"] for seg in segments)


def transcribe_wav(
    wav_path: str,
    *,
    model_size: str = _DEFAULT_MODEL_SIZE,
    device: str = _DEFAULT_DEVICE,
    compute_type: str = _DEFAULT_COMPUTE_TYPE,
    beam_size: int = _DEFAULT_BEAM_SIZE,
    vad_filter: bool = False,
    condition_on_previous_text: bool = True,
    progress_callback: Callable[[float], None] | None = None,
) -> str:
    """Transcribe a WAV file using faster-whisper.

    Args:
        wav_path: Path to the WAV file.
        model_size: Whisper model size (tiny, base, small, medium, large).
        device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
        beam_size: Beam search width. Lower = faster, higher = more accurate.
        vad_filter: Enable Silero VAD to filter non-speech audio.
        condition_on_previous_text: Use previous segment as prompt for next.
        progress_callback: Called with progress fraction (0.0-1.0) after each
            segment, based on segment end time / audio duration.
    """
    logger.info("Transcribing with model '%s'...", model_size)

    audio_duration = 0.0
    try:
        with wave.open(wav_path, "rb") as wf:
            audio_duration = wf.getnframes() / wf.getframerate()
    except Exception:
        logger.warning("Could not read WAV duration from %s", wav_path)

    try:
        model = get_or_create_model(
            model_size=model_size, device=device, compute_type=compute_type
        )
        seg_list = _run_transcription(
            model,
            wav_path,
            audio_duration=audio_duration,
            beam_size=beam_size,
            vad_filter=vad_filter,
            condition_on_previous_text=condition_on_previous_text,
            progress_callback=progress_callback,
        )
        return _segments_to_text(seg_list)
    except Exception as e:
        logger.error(
            "Failed to load Whisper model '%s': %s\n"
            "Ensure faster-whisper is installed and you have internet "
            "connectivity for initial model download.",
            model_size,
            e,
        )
        raise


def transcribe_wav_segments(
    wav_path: str,
    *,
    model_size: str = _DEFAULT_MODEL_SIZE,
    device: str = _DEFAULT_DEVICE,
    compute_type: str = _DEFAULT_COMPUTE_TYPE,
    beam_size: int = _DEFAULT_BEAM_SIZE,
    vad_filter: bool = False,
    condition_on_previous_text: bool = True,
    progress_callback: Callable[[float], None] | None = None,
) -> list[dict]:
    """Transcribe a WAV file and return timestamped segments.

    Same interface as transcribe_wav but returns a list of
    {"start": float, "end": float, "text": str} dicts.

    Args:
        wav_path: Path to the WAV file.
        model_size: Whisper model size (tiny, base, small, medium, large).
        device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
        beam_size: Beam search width. Lower = faster, higher = more accurate.
        vad_filter: Enable Silero VAD to filter non-speech audio.
        condition_on_previous_text: Use previous segment as prompt for next.
        progress_callback: Called with progress fraction (0.0-1.0) after each
            segment, based on segment end time / audio duration.
    """
    logger.info("Transcribing with model '%s'...", model_size)

    audio_duration = 0.0
    try:
        with wave.open(wav_path, "rb") as wf:
            audio_duration = wf.getnframes() / wf.getframerate()
    except Exception:
        logger.warning("Could not read WAV duration from %s", wav_path)

    try:
        model = get_or_create_model(
            model_size=model_size, device=device, compute_type=compute_type
        )
        return _run_transcription(
            model,
            wav_path,
            audio_duration=audio_duration,
            beam_size=beam_size,
            vad_filter=vad_filter,
            condition_on_previous_text=condition_on_previous_text,
            progress_callback=progress_callback,
        )
    except Exception as e:
        logger.error(
            "Failed to load Whisper model '%s': %s\n"
            "Ensure faster-whisper is installed and you have internet "
            "connectivity for initial model download.",
            model_size,
            e,
        )
        raise


def transcribe_audio(
    audio_data: np.ndarray,
    *,
    model_size: str = _DEFAULT_MODEL_SIZE,
    device: str = _DEFAULT_DEVICE,
    compute_type: str = _DEFAULT_COMPUTE_TYPE,
    beam_size: int = _DEFAULT_BEAM_SIZE,
    vad_filter: bool = True,
    condition_on_previous_text: bool = True,
    progress_callback: Callable[[float], None] | None = None,
) -> str:
    """Transcribe raw audio data (int16 numpy array) using faster-whisper.

    Passes the audio directly to the model as a float32 array, avoiding
    temp WAV file I/O. Used by ChunkManager for individual chunks.

    Args:
        audio_data: int16 numpy array of audio samples.
        model_size: Whisper model size (tiny, base, small, medium, large).
        device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
        beam_size: Beam search width. Lower = faster, higher = more accurate.
        vad_filter: Enable Silero VAD to filter non-speech audio.
        condition_on_previous_text: Use previous segment as prompt for next.
        progress_callback: Called with progress fraction (0.0-1.0).
    """
    logger.info("Transcribing with model '%s'...", model_size)
    audio_duration = len(audio_data) / SAMPLE_RATE

    # Convert int16 to float32 normalized [-1.0, 1.0] for faster-whisper
    audio_float = audio_data.flatten().astype(np.float32) / 32768.0

    try:
        model = get_or_create_model(
            model_size=model_size, device=device, compute_type=compute_type
        )
        seg_list = _run_transcription(
            model,
            audio_float,
            audio_duration=audio_duration,
            beam_size=beam_size,
            vad_filter=vad_filter,
            condition_on_previous_text=condition_on_previous_text,
            progress_callback=progress_callback,
        )
        return _segments_to_text(seg_list)
    except Exception as e:
        logger.error("Transcription failed: %s", e)
        raise


def transcribe_audio_segments(
    audio_data: np.ndarray,
    *,
    model_size: str = _DEFAULT_MODEL_SIZE,
    device: str = _DEFAULT_DEVICE,
    compute_type: str = _DEFAULT_COMPUTE_TYPE,
    beam_size: int = _DEFAULT_BEAM_SIZE,
    vad_filter: bool = True,
    condition_on_previous_text: bool = True,
    progress_callback: Callable[[float], None] | None = None,
) -> list[dict]:
    """Transcribe raw audio data and return timestamped segments.

    Same interface as transcribe_audio but returns a list of
    {"start": float, "end": float, "text": str} dicts.

    Args:
        audio_data: int16 numpy array of audio samples.
        model_size: Whisper model size (tiny, base, small, medium, large).
        device: Inference device — "cpu", "cuda", or "auto".
        compute_type: Model precision — "int8", "float16", "float32".
        beam_size: Beam search width. Lower = faster, higher = more accurate.
        vad_filter: Enable Silero VAD to filter non-speech audio.
        condition_on_previous_text: Use previous segment as prompt for next.
        progress_callback: Called with progress fraction (0.0-1.0).
    """
    logger.info("Transcribing with model '%s'...", model_size)
    audio_duration = len(audio_data) / SAMPLE_RATE

    # Convert int16 to float32 normalized [-1.0, 1.0] for faster-whisper
    audio_float = audio_data.flatten().astype(np.float32) / 32768.0

    try:
        model = get_or_create_model(
            model_size=model_size, device=device, compute_type=compute_type
        )
        return _run_transcription(
            model,
            audio_float,
            audio_duration=audio_duration,
            beam_size=beam_size,
            vad_filter=vad_filter,
            condition_on_previous_text=condition_on_previous_text,
            progress_callback=progress_callback,
        )
    except Exception as e:
        logger.error("Transcription failed: %s", e)
        raise


def _sanitize_transcript(text: str) -> str:
    """Replace characters that can't be encoded in the console's charset.

    Whisper occasionally hallucinates non-Latin scripts (Georgian, CJK, etc.)
    from ambient noise. These crash on Windows cp1252 stdout. Replace them
    with '?' to ensure output always succeeds.
    """
    encoding = sys.stdout.encoding or "utf-8"
    return text.encode(encoding, errors="replace").decode(encoding, errors="replace")
